107 setup entwicklung für wls service wahlvorbereitung
it-at-m/Wahllokalsystem pull request #219
Opened 2024-05-06 10:20 UTC by GerhardPx

# Beschreibung:

Initiale Erstellung des Wahlvorbereitung-Services

## Definition of Done (DoD):

### Backend ###
- [x] Doku aktualisiert
- [x] Swagger-API vollständig
- [x] Unit-Tests gepflegt
- [x] Integrationstests gepflegt

### Dokumentation
- [x] Links geprüft

Closes #107

2024-05-07 05:11 UTC, MrSebastian requested changes
Wie sieht es mit den Default-Tests aus? Diese müsste noch ergänzt werden.

2024-05-07 05:11 UTC, MrSebastian commented on .github/workflows/wls-wahlvorbereitung_push-dev.yml
> +      - '.github/workflows/wls-wahlvorbereitung-service_push-dev.yml'
Die Name hier entspricht dem Schema, aber der Dateiname selber nicht. Nach `wahlvorbereitung` fehlt `-service`

2024-05-07 05:11 UTC, MrSebastian commented on stack/oracle-database/add-user-on-startup.sql
> +GRANT CONNECT, RESOURCE, CREATE SESSION TO wls_infomanagement_service;
das sollte erst mit dem PR zum Infomanagement-Service kommen, bzw, schon enthalten sein. Kannst du eventuell den aktuellen dev-Branch bei dir rein mergen?

2024-05-07 05:11 UTC, MrSebastian commented on wls-wahlvorbereitung-service/src/main/java/de/muenchen/oss/wahllokalsystem/wahlvorbereitung/configuration/NoSecurityConfiguration.java
> +                .csrf(AbstractHttpConfigurer::disable);
vllt. kannst du mir kurz direkt deine Begründung für deine Auflösung schicken

2024-05-07 05:11 UTC, MrSebastian commented on wls-wahlvorbereitung-service/sso-config/sso-authorisation.json
> +{
file wird nicht benötigt und kann daher gelöscht werden

2024-05-07 05:11 UTC, MrSebastian commented on wls-wahlvorbereitung-service/sso-config/sso-client.json
> +{
file wird nicht benötigt und kann daher gelöscht werden

2024-05-08 12:19 UTC, GerhardPx commented on stack/oracle-database/add-user-on-startup.sql
> +GRANT CONNECT, RESOURCE, CREATE SESSION TO wls_infomanagement_service;
habe ich bereits. Das war eines der resolved conflicts, da ist wohl irgendwas schiefgelaufen

2024-05-08 12:22 UTC, GerhardPx commented on wls-wahlvorbereitung-service/src/main/java/de/muenchen/oss/wahllokalsystem/wahlvorbereitung/configuration/NoSecurityConfiguration.java
> +                .csrf(AbstractHttpConfigurer::disable);
Da ich gesehen habe, dass das beim PR aufsetzen des Infomanagement auch so gehandhabt wurde, habe ich das übernommen. War das ein Fehler?

2024-05-08 13:05 UTC, GerhardPx commented
> Wie sieht es mit den Default-Tests aus? Diese müsste noch ergänzt werden.

Da müsste man natürlich auch so schlau sein und die mitcommiten in den unversioned files 😄 sind in den neuen commits drin

2024-05-08 13:07 UTC, MrSebastian commented
:D wenn es immer so einfach wäre

2024-05-08 14:20 UTC, MrSebastian requested changes
Du kannst auch den [Test zu UserInfoAuthoritiesServiceTest](https://github.com/it-at-m/Wahllokalsystem/pull/200/commits/e844f96d6fa11e10351eb7825b2a2ae52781b96e) übernehmen.

2024-05-08 14:20 UTC, MrSebastian commented on wls-wahlvorbereitung-service/src/test/java/de/muenchen/oss/wahllokalsystem/wahlvorbereitungservice/configuration/nfcconverter/NfcHelperTest.java
> +    void nfcConverterString() {
Bei dem Test könntest du noch die Anpassungen die durch dich inspiriert wurden ergänzen: https://github.com/it-at-m/Wahllokalsystem/blob/dev/wls-briefwahl-service/src/test/java/de/muenchen/oss/wahllokalsystem/briefwahlservice/configuration/nfcconverter/NfcHelperTest.java

2024-05-08 14:20 UTC, MrSebastian commented on wls-wahlvorbereitung-service/src/main/java/de/muenchen/oss/wahllokalsystem/wahlvorbereitungservice/security/AuthUtils.java
> +        }
Gerne deinen Vorschlag zum Patternmatching auch hier verwenden (https://github.com/it-at-m/Wahllokalsystem/pull/200/commits/d53185be88bb05a6d20f886d37a9348454564d15). Bei `UserInfoAuthoritiesService` hattest du es bereits angewendet.

2024-05-08 14:26 UTC, MrSebastian commented on wls-wahlvorbereitung-service/src/test/java/de/muenchen/oss/wahllokalsystem/wahlvorbereitungservice/configuration/CacheControlConfigurationTest.java
> +    @Disabled
Bitte hierzu analog ein Issue aufmachen damit wir das Thema auf dem Schirm behalten (analog zu #201 #207)

2024-05-08 14:57 UTC, GerhardPx commented on wls-wahlvorbereitung-service/src/test/java/de/muenchen/oss/wahllokalsystem/wahlvorbereitungservice/configuration/CacheControlConfigurationTest.java
> +    @Disabled
👍  #230

2024-05-08 15:15 UTC, MrSebastian approved these changes

2024-05-08 15:19 UTC, merged