165 implementierung von konfiguration wahltag
it-at-m/Wahllokalsystem pull request #244
Opened 2024-05-16 13:34 UTC by dragonfly28

# Beschreibung:

*Beschreben Sie hier die wesentlichen Aufgaben, die damit erledigt wurden und geben sie Hinweise zum Review.*

## Definition of Done (DoD):

### Backend ###
- [ ] Doku aktualisiert
- [x] Swagger-API vollständig
- [x] Unit-Tests gepflegt
- [x] Integrationstests gepflegt
- [ ] Beispiel-Requests gepflegt

# Referenzen[^1]:

Closes #165

> [^1]: _Nicht zutreffende Referenzen vor dem Speichern entfernen_

2024-05-17 07:16 UTC, MrSebastian requested changes
sieht sehr gut aus. Es fehlt ein Test, ein paar Parameter sollten anders sein. Ansonmsten gibt es einige Optimierungsmöglichkeiten und hauptsächlich ein paar Leerzeilen aus meiner Sicht zu viel.

2024-05-17 07:16 UTC, MrSebastian commented on wls-infomanagement-service/pom.xml
> +
unnötige neue Leerzeile

2024-05-17 07:16 UTC, MrSebastian commented on wls-infomanagement-service/src/main/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/domain/wahltag/KonfigurierterWahltag.java
> +    @JsonSerialize(using = LocalDateSerializer.class)
bei Entität nicht erforderlich

2024-05-17 07:16 UTC, MrSebastian commented on wls-infomanagement-service/src/main/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/domain/wahltag/KonfigurierterWahltag.java
> +import de.muenchen.oss.wahllokalsystem.infomanagementservice.rest.wahltag.WahltagStatus;
aus meiner Sicht eine unschöne Querbeziehung in ein anderes Package. Sollte aus meiner Sicht entweder in ein common-package oder die Domain erhält ihren eigenen Status.

2024-05-17 07:16 UTC, MrSebastian commented on wls-infomanagement-service/src/main/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/service/wahltag/KonfigurierterWahltagModel.java
> +import de.muenchen.oss.wahllokalsystem.infomanagementservice.rest.wahltag.WahltagStatus;
aus meiner Sicht eine unschöne Querbeziehung in ein anderes Package. Sollte aus meiner Sicht entweder in ein common-package oder die Domain erhält ihren eigenen Status.

2024-05-17 07:16 UTC, MrSebastian commented on wls-infomanagement-service/src/main/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/service/wahltag/KonfigurierterWahltagModelMapper.java
> +public interface KonfigurierterWahltagModelMapper {
hat keine eignen Tests

2024-05-17 07:16 UTC, MrSebastian commented on wls-infomanagement-service/src/main/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/service/wahltag/KonfigurierterWahltagService.java
> +
```suggestion
    public KonfigurierterWahltagModel getKonfigurierterWahltag() {
```

2024-05-17 07:16 UTC, MrSebastian commented on wls-infomanagement-service/src/main/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/service/wahltag/KonfigurierterWahltagService.java
> +
```suggestion
    public void setKonfigurierterWahltag(KonfigurierterWahltagModel konfigurierterWahltagModel) {
```

2024-05-17 07:16 UTC, MrSebastian commented on wls-infomanagement-service/src/main/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/service/wahltag/KonfigurierterWahltagService.java
> +            konfigurierterWahltagRepository.saveAll(wahltage);
geht das eventuell direkt über die Datenbank?

2024-05-17 07:16 UTC, MrSebastian commented on wls-infomanagement-service/src/main/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/service/wahltag/KonfigurierterWahltagService.java
> +
```suggestion
    public void deleteKonfigurierterWahltag(KonfigurierterWahltagModel konfigurierterWahltagModel) {
```

2024-05-17 07:16 UTC, MrSebastian commented on wls-infomanagement-service/src/main/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/service/wahltag/KonfigurierterWahltagService.java
> +        konfigurierteWahltage.sort(Comparator.comparing(KonfigurierterWahltag::getWahltag));
das könnten wir auch an die Datenbank auslagern

2024-05-17 07:16 UTC, MrSebastian commented on wls-infomanagement-service/src/main/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/service/wahltag/KonfigurierterWahltagService.java
> +
```suggestion
    public List<KonfigurierterWahltagModel> getKonfigurierteWahltage() {
```

2024-05-17 07:16 UTC, MrSebastian commented on wls-infomanagement-service/src/main/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/service/wahltag/KonfigurierterWahltagService.java
> +
```suggestion
    public boolean isWahltagActive(KonfigurierterWahltagModel konfigurierterWahltagModel) {
```

2024-05-17 07:16 UTC, MrSebastian commented on wls-infomanagement-service/src/main/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/service/wahltag/KonfigurierterWahltagService.java
> +        Optional<KonfigurierterWahltag> konfigurierterWahltag = konfigurierterWahltagRepository.findById(konfigurierterWahltagModel.wahltagID());
```suggestion
        val konfigurierterWahltag = konfigurierterWahltagRepository.findById(konfigurierterWahltagModel.wahltagID());
```

2024-05-17 07:16 UTC, MrSebastian commented on wls-infomanagement-service/src/main/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/service/wahltag/KonfigurierterWahltagService.java
> +        return konfigurierterWahltag.isPresent() && !konfigurierterWahltag.get().getWahltagStatus().equals(WahltagStatus.INAKTIV);
Alternative:

```suggestion
        return konfigurierterWahltag.map(status -> status.getWahltagStatus() == WahltagStatus.AKTIV).orElse(false);
```

2024-05-17 07:16 UTC, MrSebastian commented on wls-infomanagement-service/src/main/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/service/wahltag/KonfigurierterWahltagValidator.java
> +
```suggestion
```

2024-05-17 07:16 UTC, MrSebastian commented on wls-infomanagement-service/src/main/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/service/wahltag/KonfigurierterWahltagValidator.java
> +            throw FachlicheWlsException.withCode(DELETE_KONFIGURIERTERWAHLTAG_PARAMETER_UNVOLLSTAENDIG.code()).inService(serviceIDFormatter.getId())
```suggestion
    public void validDeleteModelOrThrow(KonfigurierterWahltagModel konfigurierterWahltag) {
        if (konfigurierterWahltag.wahltagID() == null || konfigurierterWahltag.wahltagID().isEmpty()) {
            throw FachlicheWlsException.withCode(DELETE_KONFIGURIERTERWAHLTAG_PARAMETER_UNVOLLSTAENDIG.code()).inService(serviceIDFormatter.getId())
```

2024-05-17 07:16 UTC, MrSebastian commented on wls-infomanagement-service/src/test/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/rest/wahltag/KonfigurierterWahltagControllerIntegrationTest.java
> +
```suggestion
```

2024-05-17 07:16 UTC, MrSebastian commented on wls-infomanagement-service/src/test/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/rest/wahltag/KonfigurierterWahltagControllerIntegrationTest.java
> +            Assertions.assertThat(responseGetBody).isEqualTo(expectedResponseGetBody);
könnte man über den Zugriff auf das Repo abkürzen

2024-05-17 07:16 UTC, MrSebastian commented on wls-infomanagement-service/src/test/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/rest/wahltag/KonfigurierterWahltagControllerIntegrationTest.java
> +    // Dooffall: DB hat nur inaktive Wahltage, neu setzen mit WahltagStatus.INAKTIV -> kein Wahltag
der Kommentar erfüllt aus meiner Sicht hier keinem Zweck

2024-05-17 07:16 UTC, MrSebastian commented on wls-infomanagement-service/src/test/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/rest/wahltag/KonfigurierterWahltagControllerIntegrationTest.java
> +        void overrideAktivWahltagAndReadOKWithContent() throws Exception {
Vorschlag für ein besseres Naming

```suggestion
        void overrideAktiverWahltagAndReadOKWithContent() throws Exception {
```

oder die englische Variante

2024-05-17 07:16 UTC, MrSebastian commented on wls-infomanagement-service/src/test/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/rest/wahltag/KonfigurierterWahltagControllerIntegrationTest.java
> +            Assertions.assertThat(responseGetBody).isEqualTo(expectedResponseGetBody);
auch hier könnte man wieder direkt auf das Repo gehen

2024-05-17 07:16 UTC, MrSebastian commented on wls-infomanagement-service/src/test/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/rest/wahltag/KonfigurierterWahltagControllerTest.java
> +
```suggestion
```

2024-05-17 07:16 UTC, MrSebastian commented on wls-infomanagement-service/src/test/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/rest/wahltag/KonfigurierterWahltagControllerTest.java
> +
```suggestion
```

2024-05-17 07:16 UTC, MrSebastian commented on wls-infomanagement-service/src/test/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/rest/wahltag/KonfigurierterWahltagControllerTest.java
> +
```suggestion
```

2024-05-17 07:16 UTC, MrSebastian commented on wls-infomanagement-service/src/test/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/rest/wahltag/KonfigurierterWahltagControllerTest.java
> +
```suggestion
```

2024-05-17 07:16 UTC, MrSebastian commented on wls-infomanagement-service/src/test/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/rest/wahltag/KonfigurierterWahltagControllerTest.java
> +
```suggestion
```

2024-05-17 07:16 UTC, MrSebastian commented on wls-infomanagement-service/src/test/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/rest/wahltag/KonfigurierterWahltagControllerTest.java
> +
```suggestion
```

2024-05-17 07:16 UTC, MrSebastian commented on wls-infomanagement-service/src/test/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/rest/wahltag/KonfigurierterWahltagControllerTest.java
> +    class IsWahltagActive {
könnte man auf einen Test reduzieren da der Controller lediglich das Ergebnis vom Service durchreicht

2024-05-17 07:16 UTC, MrSebastian commented on wls-infomanagement-service/src/main/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/service/wahltag/KonfigurierterWahltagService.java
> +    public void deleteKonfigurierterWahltag(KonfigurierterWahltagModel konfigurierterWahltagModel) {
Als Parameter genügt die ID. Die weiteren Properties werden nicht benötigt.

2024-05-17 07:16 UTC, MrSebastian commented on wls-infomanagement-service/src/main/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/service/wahltag/KonfigurierterWahltagService.java
> +    public boolean isWahltagActive(KonfigurierterWahltagModel konfigurierterWahltagModel) {
Hier genügt die Wahltag ID als Parameter.

2024-05-17 07:36 UTC, MrSebastian commented on wls-infomanagement-service/src/main/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/domain/wahltag/KonfigurierterWahltag.java
> +    @JsonSerialize(using = LocalDateSerializer.class)
done mit fce227025b31409d0a54bce4a66f47b44a55a6a5

2024-05-17 07:36 UTC, MrSebastian commented on wls-infomanagement-service/src/main/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/service/wahltag/KonfigurierterWahltagModelMapper.java
> +public interface KonfigurierterWahltagModelMapper {
done mit 9b72547130114d21141681ac35c73a3ee7f3dcc2

2024-05-17 10:38 UTC, MrSebastian commented on wls-infomanagement-service/src/main/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/service/wahltag/KonfigurierterWahltagModel.java
> +import de.muenchen.oss.wahllokalsystem.infomanagementservice.rest.wahltag.WahltagStatus;
@FabianWilms hatte die Gute Idee dass wir in Model und der DB isActive: true/false verwenden.

2024-05-17 10:59 UTC, MrSebastian commented on wls-infomanagement-service/src/main/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/service/wahltag/KonfigurierterWahltagService.java
> +            konfigurierterWahltagRepository.saveAll(wahltage);
fixed mit d47b424bd8ca99f5a438f96b1819cc0f614dbfad

2024-05-17 11:02 UTC, MrSebastian commented on wls-infomanagement-service/src/main/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/service/wahltag/KonfigurierterWahltagService.java
> +
fixed mit c1a2361c6bd795e50a2747a608f0b1400f43ebda

2024-05-17 11:03 UTC, MrSebastian commented on wls-infomanagement-service/src/main/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/service/wahltag/KonfigurierterWahltagService.java
> +
fixed mit c1a2361c6bd795e50a2747a608f0b1400f43ebda

2024-05-17 11:03 UTC, MrSebastian commented on wls-infomanagement-service/src/main/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/service/wahltag/KonfigurierterWahltagService.java
> +
fixed mit c1a2361c6bd795e50a2747a608f0b1400f43ebda

2024-05-17 11:03 UTC, MrSebastian commented on wls-infomanagement-service/src/main/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/service/wahltag/KonfigurierterWahltagService.java
> +
fixed mit c1a2361c6bd795e50a2747a608f0b1400f43ebda

2024-05-17 11:05 UTC, MrSebastian commented on wls-infomanagement-service/src/test/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/rest/wahltag/KonfigurierterWahltagControllerTest.java
> +
done mit c1a2361c6bd795e50a2747a608f0b1400f43ebda

2024-05-17 11:05 UTC, MrSebastian commented on wls-infomanagement-service/src/test/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/rest/wahltag/KonfigurierterWahltagControllerTest.java
> +
done mit c1a2361c6bd795e50a2747a608f0b1400f43ebda

2024-05-17 11:05 UTC, MrSebastian commented on wls-infomanagement-service/src/test/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/rest/wahltag/KonfigurierterWahltagControllerTest.java
> +
done mit c1a2361c6bd795e50a2747a608f0b1400f43ebda

2024-05-17 11:05 UTC, MrSebastian commented on wls-infomanagement-service/src/test/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/rest/wahltag/KonfigurierterWahltagControllerTest.java
> +
done mit c1a2361c6bd795e50a2747a608f0b1400f43ebda

2024-05-17 11:05 UTC, MrSebastian commented on wls-infomanagement-service/src/test/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/rest/wahltag/KonfigurierterWahltagControllerTest.java
> +
done mit c1a2361c6bd795e50a2747a608f0b1400f43ebda

2024-05-17 12:03 UTC, MrSebastian commented on wls-infomanagement-service/src/main/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/domain/wahltag/KonfigurierterWahltag.java
> +import de.muenchen.oss.wahllokalsystem.infomanagementservice.rest.wahltag.WahltagStatus;
done mit d8916d77f7342fd47265df05aebcdb54b0e7ef90

2024-05-17 12:03 UTC, MrSebastian commented on wls-infomanagement-service/src/main/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/service/wahltag/KonfigurierterWahltagModel.java
> +import de.muenchen.oss.wahllokalsystem.infomanagementservice.rest.wahltag.WahltagStatus;
done mit d8916d77f7342fd47265df05aebcdb54b0e7ef90

2024-05-17 12:05 UTC, MrSebastian commented on wls-infomanagement-service/src/test/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/rest/wahltag/KonfigurierterWahltagControllerTest.java
> +
done mit c1a2361c6bd795e50a2747a608f0b1400f43ebda

2024-05-17 12:06 UTC, MrSebastian commented on wls-infomanagement-service/src/main/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/service/wahltag/KonfigurierterWahltagValidator.java
> +
done mit 7a4f3b0952d35d6ab8d36c2e24728c799533bd02

2024-05-17 12:07 UTC, MrSebastian commented on wls-infomanagement-service/src/main/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/service/wahltag/KonfigurierterWahltagService.java
> +
done mit c1a2361c6bd795e50a2747a608f0b1400f43ebda

2024-05-17 12:11 UTC, MrSebastian commented on wls-infomanagement-service/src/main/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/service/wahltag/KonfigurierterWahltagService.java
> +        return konfigurierterWahltag.isPresent() && !konfigurierterWahltag.get().getWahltagStatus().equals(WahltagStatus.INAKTIV);
nach der Umstellung auf `active` hat sich die Leserlichkeit bereits verbessert

2024-05-17 12:12 UTC, MrSebastian commented on wls-infomanagement-service/src/main/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/service/wahltag/KonfigurierterWahltagValidator.java
> +            throw FachlicheWlsException.withCode(DELETE_KONFIGURIERTERWAHLTAG_PARAMETER_UNVOLLSTAENDIG.code()).inService(serviceIDFormatter.getId())
fixed mit 7a4f3b0952d35d6ab8d36c2e24728c799533bd02

2024-05-17 12:12 UTC, MrSebastian commented on wls-infomanagement-service/src/test/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/rest/wahltag/KonfigurierterWahltagControllerIntegrationTest.java
> +
done mit 1446945188d39dbd113902dc86f07d167aae3c17

2024-05-17 12:13 UTC, MrSebastian commented on wls-infomanagement-service/src/test/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/rest/wahltag/KonfigurierterWahltagControllerTest.java
> +    class IsWahltagActive {
kann aber auch so bleiben

2024-05-17 12:24 UTC, MrSebastian commented on wls-infomanagement-service/src/main/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/service/wahltag/KonfigurierterWahltagService.java
> +    public void deleteKonfigurierterWahltag(KonfigurierterWahltagModel konfigurierterWahltagModel) {
done mit a7b138f7e2c6d60ff0336e23f5903e9dca5c3885

2024-05-17 12:24 UTC, MrSebastian commented on wls-infomanagement-service/src/main/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/service/wahltag/KonfigurierterWahltagService.java
> +    public boolean isWahltagActive(KonfigurierterWahltagModel konfigurierterWahltagModel) {
done mit a7b138f7e2c6d60ff0336e23f5903e9dca5c3885

2024-05-17 12:45 UTC, MrSebastian commented on wls-infomanagement-service/src/main/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/service/wahltag/KonfigurierterWahltagService.java
> +        konfigurierteWahltage.sort(Comparator.comparing(KonfigurierterWahltag::getWahltag));
done mit c459bd2058cc9b43ef0f6edbb9ebff4c67bd3d84

2024-05-17 12:45 UTC, MrSebastian commented on wls-infomanagement-service/src/test/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/rest/wahltag/KonfigurierterWahltagControllerIntegrationTest.java
> +    // Dooffall: DB hat nur inaktive Wahltage, neu setzen mit WahltagStatus.INAKTIV -> kein Wahltag
done mit 3c6495ab52a6b1d45d5531559c6071a4106926fb

2024-05-17 12:45 UTC, MrSebastian commented on wls-infomanagement-service/src/test/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/rest/wahltag/KonfigurierterWahltagControllerIntegrationTest.java
> +            Assertions.assertThat(responseGetBody).isEqualTo(expectedResponseGetBody);
für einen Integrationstest passt es schon

2024-05-17 12:46 UTC, MrSebastian commented on wls-infomanagement-service/src/test/java/de/muenchen/oss/wahllokalsystem/infomanagementservice/rest/wahltag/KonfigurierterWahltagControllerIntegrationTest.java
> +            Assertions.assertThat(responseGetBody).isEqualTo(expectedResponseGetBody);
für einen Integrationstest passt es schon

2024-05-17 12:49 UTC, MrSebastian approved these changes

2024-05-21 11:23 UTC, GerhardPx approved these changes
Sieht gut aus, keine weiteren Anmerkungen. Die einzigen Fragen haben sich dann in der IDE erübrigt.

2024-05-21 11:55 UTC, merged