160 implementierung eröffnungsuhrzeit
it-at-m/Wahllokalsystem pull request #299
Opened 2024-06-13 09:28 UTC by Nic12345678

# Beschreibung:

Implementierung der Eröffnungsuhrzeit analog zu https://github.com/it-at-m/Wahllokalsystem/issues/162

## Definition of Done (DoD):

### Backend ###
- [X] Swagger-API vollständig
- [X] Unit-Tests gepflegt
- [X] Integrationstests gepflegt
- [X] Beispiel-Requests gepflegt

Verwandt mit Issue #162

Closes #160

2024-06-13 13:01 UTC, MrSebastian requested changes
ein paar Kleinigkeiten und bitte Keycloak-Migration noch pflegen, ansonsten sieht es gut aus

2024-06-13 13:01 UTC, MrSebastian commented on wls-wahlvorbereitung-service/src/main/java/de/muenchen/oss/wahllokalsystem/wahlvorbereitungservice/rest/eroeffnungsuhrzeit/EroeffnungsUhrzeitController.java
> +    @Operation(description = "Laden der Eroeffnungsuhrzeit des Urnenwahllokals {wahlbezirkID}")
Ist es wirklich auf Urnenwahl beschränkt?

2024-06-13 13:01 UTC, MrSebastian commented on wls-wahlvorbereitung-service/src/main/java/de/muenchen/oss/wahllokalsystem/wahlvorbereitungservice/rest/eroeffnungsuhrzeit/EroeffnungsUhrzeitController.java
> +    @Operation(description = "Aktualisiert die Eroeffnungsuhrzeit des Urnenwahllokals {wahlbezirkID}")
Ist es wirklich auf Urnenwahl beschränkt?

2024-06-13 13:01 UTC, MrSebastian commented on wls-wahlvorbereitung-service/src/main/java/de/muenchen/oss/wahllokalsystem/wahlvorbereitungservice/service/eroeffnungsuhrzeit/EroeffnungsUhrzeitService.java
> +            eroeffnungsUhrzeitRepository.save(eroeffnungsUhrzeitModelMapper.toEntity(eroeffnungsuhrzeitToSet));
im Altsystem wurde hier ein spezieller Logger ergänzt. Ist der nicht mehr notwendig?

2024-06-13 13:01 UTC, MrSebastian commented on wls-wahlvorbereitung-service/src/main/resources/db/migrations/h2/V4_0__createTableEroeffnungsuhrzeit.sql
> +create table Eroeffnungsuhrzeit
V4 wird bereits durch #298 erzeugt. Ich schlage vor wir Planen diesen PR danach ein und können so hier `V5` verwenden.

2024-06-13 13:01 UTC, MrSebastian commented on wls-wahlvorbereitung-service/src/main/resources/db/migrations/oracle/V4_0__createTableEroeffnungsuhrzeit.sql
> +create table Eroeffnungsuhrzeit
V4 wird bereits durch #298 erzeugt. Ich schlage vor wir Planen diesen PR danach ein und können so hier `V5` verwenden.

2024-06-13 13:01 UTC, MrSebastian commented on wls-wahlvorbereitung-service/src/main/resources/db/migrations/h2/V4_0__createTableEroeffnungsuhrzeit.sql
> +    primary key (wahlbezirkid)
Hat IntelliJ bei dir nicht formartiert?
```suggestion
    wahlbezirkid       varchar(1000) not null,
    eroeffnungsuhrzeit TIMESTAMP     not null,
    primary key (wahlbezirkid)
```

2024-06-13 13:01 UTC, MrSebastian commented on wls-wahlvorbereitung-service/src/main/resources/db/migrations/oracle/V4_0__createTableEroeffnungsuhrzeit.sql
> +    primary key (wahlbezirkid)
Hat IntelliJ bei dir nicht formartiert?

```suggestion
    wahlbezirkid       varchar(1000) not null,
    eroeffnungsuhrzeit TIMESTAMP     not null,
    primary key (wahlbezirkid)
```

2024-06-13 13:01 UTC, MrSebastian commented on wls-wahlvorbereitung-service/src/test/java/de/muenchen/oss/wahllokalsystem/wahlvorbereitungservice/service/eroeffnungsuhrzeit/EroeffnungsUhrzeitSecurityTest.java
> +
Leerzeile kann raus

```suggestion
        void wlsExceptionOnRepoWriteAuthorityMissing() {
```

2024-06-13 13:01 UTC, MrSebastian commented on wls-wahlvorbereitung-service/src/test/java/de/muenchen/oss/wahllokalsystem/wahlvorbereitungservice/service/eroeffnungsuhrzeit/EroeffnungsUhrzeitSecurityTest.java
> +            String[] ALL_AUTHORITIES_POST_EROEFFNUNGSUHRZEIT_WHITHOUT_REPO_WRITE = Arrays.stream(Authorities.ALL_AUTHORITIES_POST_EROEFFNUNGSUHRZEIT)
optionale Vorschlag für die Einheitlichkeit

```suggestion
            val ALL_AUTHORITIES_POST_EROEFFNUNGSUHRZEIT_WHITHOUT_REPO_WRITE = Arrays.stream(Authorities.ALL_AUTHORITIES_POST_EROEFFNUNGSUHRZEIT)
```

2024-06-13 13:06 UTC, Nic12345678 commented on wls-wahlvorbereitung-service/src/main/java/de/muenchen/oss/wahllokalsystem/wahlvorbereitungservice/rest/eroeffnungsuhrzeit/EroeffnungsUhrzeitController.java
> +    @Operation(description = "Laden der Eroeffnungsuhrzeit des Urnenwahllokals {wahlbezirkID}")
Wirklich nicht :) 
```suggestion
    @Operation(description = "Laden der Eroeffnungsuhrzeit des Urnenwahllokals {wahlbezirkID}")
```
```suggestion
    @Operation(description = "Laden der Eroeffnungsuhrzeit des Wahllokals {wahlbezirkID}")
```

2024-06-13 13:09 UTC, Nic12345678 commented on wls-wahlvorbereitung-service/src/main/java/de/muenchen/oss/wahllokalsystem/wahlvorbereitungservice/rest/eroeffnungsuhrzeit/EroeffnungsUhrzeitController.java
> +    @Operation(description = "Aktualisiert die Eroeffnungsuhrzeit des Urnenwahllokals {wahlbezirkID}")
```suggestion
    @Operation(description = "Aktualisiert die Eroeffnungsuhrzeit des Wahllokals {wahlbezirkID}")
```

2024-06-13 13:17 UTC, Nic12345678 commented on wls-wahlvorbereitung-service/src/main/resources/db/migrations/h2/V4_0__createTableEroeffnungsuhrzeit.sql
> +    primary key (wahlbezirkid)
ich habe spotless apply laufen lassen, aber nicht gemacht.

2024-06-13 13:19 UTC, Nic12345678 commented on wls-wahlvorbereitung-service/src/main/resources/db/migrations/oracle/V4_0__createTableEroeffnungsuhrzeit.sql
> +    primary key (wahlbezirkid)
Noch einmal die Antwort, nein hat er nicht.
Noch einmal weil, ich weiß es nicht was Chrome im Moment hat, alle Bereiche mit suggested change erscheinen doppelt

2024-06-13 13:20 UTC, Nic12345678 commented on wls-wahlvorbereitung-service/src/test/java/de/muenchen/oss/wahllokalsystem/wahlvorbereitungservice/service/eroeffnungsuhrzeit/EroeffnungsUhrzeitSecurityTest.java
> +
okydoky

2024-06-13 13:26 UTC, Nic12345678 commented on wls-wahlvorbereitung-service/src/main/resources/db/migrations/oracle/V4_0__createTableEroeffnungsuhrzeit.sql
> +create table Eroeffnungsuhrzeit
ok.

2024-06-13 13:27 UTC, Nic12345678 commented on wls-wahlvorbereitung-service/src/main/resources/db/migrations/h2/V4_0__createTableEroeffnungsuhrzeit.sql
> +create table Eroeffnungsuhrzeit
ok

2024-06-13 13:48 UTC, Nic12345678 commented on wls-wahlvorbereitung-service/src/main/java/de/muenchen/oss/wahllokalsystem/wahlvorbereitungservice/service/eroeffnungsuhrzeit/EroeffnungsUhrzeitService.java
> +            eroeffnungsUhrzeitRepository.save(eroeffnungsUhrzeitModelMapper.toEntity(eroeffnungsuhrzeitToSet));
Doch danke, ich habe auch unter Package de.muenchen.oss.wahllokalsystem.wahlvorbereitungservice.filter wie im alten einen MDC Filter gesetzt. Anscheinend er gibt aus in dem Log in Openshift den Benutzernamen mit dem die Requests kommen. Bin mir nicht so sicher ..

2024-06-13 16:22 UTC, MrSebastian commented on stack/keycloak/migration/add-authorities-wahlvorbereitung-eroeffnungsuhrzeit.yml
> +author: dragonfly28
hier bitte deinen Namen eintragen

2024-06-14 09:04 UTC, Nic12345678 commented on stack/keycloak/migration/add-authorities-wahlvorbereitung-eroeffnungsuhrzeit.yml
> +author: dragonfly28
```suggestion
author: Nic12345678
```

2024-06-14 09:05 UTC, MrSebastian approved these changes

2024-06-14 09:09 UTC, merged