153 implementierung wahldaten in eai-service
it-at-m/Wahllokalsystem pull request #334
Opened 2024-07-04 07:56 UTC by MrSebastian

# Beschreibung:

- Datenmodell
  - Wahltag -1..n-> Wahl -1..n --> Stimmzettelgebiet -1..n-> Wahlbezirk
- Das ein Wahlbezirk teil von mehreren Wahlen bzw. Stimmzettelgebieten sein kann habe ich nicht abgebildet da der Service nicht funktional vollständig sein muss sondern der funktionalen Demonstration der anderen Service dienen soll
- ❗ Änderung an API: Wrapper-Klassen für Listen wurden eingespart wenn diese keine weiteren Properties hatten
- Umwandlung von String in UUID wurde in eigene Klasse ausgelagert. Daher gab es auch Anpassungen an Wahlvorstand
- der Gedanke zu den zahlreichen Flyway-Files war die einzelnen Dateien übersichtlicher zu halten. In der Minor-Version wird eine Entität verwaltet und im Patch-Level-File dazu gibt es die Testdaten

## Definition of Done (DoD):

### Backend ###
- [x] Doku aktualisiert
  - notwendige Rechte je Endpunkt eingetragen
- [x] Swagger-API vollständig
- [X] Unit-Tests gepflegt
- [X] Integrationstests gepflegt
- [X] Beispiel-Requests gepflegt
- [X] Testdaten gepflegt: sind mit den Testdaten vom Wahlvorstand abgeglichen

### Dokumentation
- [ ] Links geprüft

### Frontend
- [ ] Doku aktualisiert
- [ ] Unit-Tests gepflegt
- [ ] Komponententests gepflegt

# Referenzen[^1]:

Verwandt mit Issue #

Closes #

> [^1]: _Nicht zutreffende Referenzen vor dem Speichern entfernen_

2024-07-05 10:25 UTC, dragonfly28 requested changes
Im Keycloak Changelog fehlt noch der Eintrag:  
`- path: add-authorities-eai-wahldaten.yml`

2024-07-05 10:25 UTC, dragonfly28 commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/domain/wahldaten/Stimmzettelgebiet.java
> +    private Stimmzettelgebietsart stimmzettelgebietart;
```suggestion
    private Stimmzettelgebietsart stimmzettelgebietsart;
```

2024-07-05 10:25 UTC, dragonfly28 commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/domain/wahldaten/Wahl.java
> +    @NotNull
```suggestion
    @NotNull
    @ToString.Include
```

2024-07-05 10:25 UTC, dragonfly28 commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/domain/wahldaten/Wahl.java
> +    @NotNull
```suggestion
    @NotNull
    @ToString.Include
```

2024-07-05 10:25 UTC, dragonfly28 commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/domain/wahldaten/Wahlbezirk.java
> +    @NotNull
```suggestion
    @NotNull
    @ToString.Include
```

2024-07-05 10:25 UTC, dragonfly28 commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/domain/wahldaten/Wahlbezirk.java
> +    @NotNull
```suggestion
    @NotNull
    @ToString.Include
```

2024-07-05 10:25 UTC, dragonfly28 commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/domain/wahldaten/Wahlbezirk.java
> +    @NotNull
```suggestion
    @NotNull
    @ToString.Include
```

2024-07-05 10:25 UTC, dragonfly28 commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/domain/wahldaten/Wahlbezirk.java
> +    private long a1;
```suggestion
    @ToString.Include
    private long a1;
```

2024-07-05 10:25 UTC, dragonfly28 commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/domain/wahldaten/Wahlbezirk.java
> +    private long a2;
```suggestion
    @ToString.Include
    private long a2;
```

2024-07-05 10:25 UTC, dragonfly28 commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/domain/wahldaten/Wahlbezirk.java
> +    private long a3;
```suggestion
    @ToString.Include
    private long a3;
```

2024-07-05 10:25 UTC, dragonfly28 commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/domain/wahldaten/WahlbezirkRepository.java
> +    List<Wahlbezirk> findWahlbezirkeWithStimmzettelgebietAndWahlAndWahltagByID(@Param("wahlbezirkID") UUID wahlbezirkID);
Ja, die beiden Methodennamen sind lang, aber sie erleichtern mir auch das Lesen und Verstehen der jeweiligen Queries.
Mit `findWahlbezirkeAndFetchParentEntities[...]` müsste ich mir für die Queries erstmal das Gehirn verbiegen um zu verstehen was hier passiert. Also meiner Meinung nach so lassen.

2024-07-05 10:25 UTC, dragonfly28 commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/exception/ExceptionConstants.java
> +    public static final ExceptionDataWrapper LOADWAHLEBZIRKE_WAHLTAG_FEHLT = new ExceptionDataWrapper("001", "Es ist kein Wahltag angegeben");
Bitte Typo `LOADWAHLEBZIRKE` ändern zu `LOADWAHLBEZIRKE` - im alten Code auch falsch, aber müssen wir ja nicht übernehmen :-)

2024-07-05 10:25 UTC, dragonfly28 commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/exception/ExceptionConstants.java
> +    public static final ExceptionDataWrapper LOADWAHLEBZIRKE_NUMMER_FEHLT = new ExceptionDataWrapper("001_1", "Es ist keine Wahltag-Nummer angegeben");
dito

2024-07-05 12:37 UTC, MrSebastian commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/exception/ExceptionConstants.java
> +    public static final ExceptionDataWrapper LOADWAHLEBZIRKE_NUMMER_FEHLT = new ExceptionDataWrapper("001_1", "Es ist keine Wahltag-Nummer angegeben");
fixed mit af3ee06e4ecd5df4e97f718ea23f6de8cb5e4a5f

2024-07-05 12:37 UTC, MrSebastian commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/exception/ExceptionConstants.java
> +    public static final ExceptionDataWrapper LOADWAHLEBZIRKE_WAHLTAG_FEHLT = new ExceptionDataWrapper("001", "Es ist kein Wahltag angegeben");
fixed mit af3ee06e4ecd5df4e97f718ea23f6de8cb5e4a5f

2024-07-05 12:37 UTC, MrSebastian commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/domain/wahldaten/Wahlbezirk.java
> +    private long a3;
fixed mit 59fa888875fbbdf5907f531d462df9e40548d293

2024-07-05 12:38 UTC, MrSebastian commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/domain/wahldaten/Wahlbezirk.java
> +    private long a2;
fixed mit 59fa888875fbbdf5907f531d462df9e40548d293

2024-07-05 12:38 UTC, MrSebastian commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/domain/wahldaten/Wahlbezirk.java
> +    private long a1;
fixed mit 59fa888875fbbdf5907f531d462df9e40548d293

2024-07-05 12:38 UTC, MrSebastian commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/domain/wahldaten/Wahlbezirk.java
> +    @NotNull
fixed mit 59fa888875fbbdf5907f531d462df9e40548d293

2024-07-05 12:38 UTC, MrSebastian commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/domain/wahldaten/Wahlbezirk.java
> +    @NotNull
fixed mit 59fa888875fbbdf5907f531d462df9e40548d293

2024-07-05 12:38 UTC, MrSebastian commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/domain/wahldaten/Wahlbezirk.java
> +    @NotNull
fixed mit 59fa888875fbbdf5907f531d462df9e40548d293

2024-07-05 12:38 UTC, MrSebastian commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/domain/wahldaten/Wahl.java
> +    @NotNull
fixed mit 59fa888875fbbdf5907f531d462df9e40548d293

2024-07-05 12:38 UTC, MrSebastian commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/domain/wahldaten/Wahl.java
> +    @NotNull
fixed mit 59fa888875fbbdf5907f531d462df9e40548d293

2024-07-05 12:38 UTC, MrSebastian commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/domain/wahldaten/Stimmzettelgebiet.java
> +    private Stimmzettelgebietsart stimmzettelgebietart;
fixed mit 4d069218a6f0a5f0b8f9ab36956922e6dc1f0da9

2024-07-08 09:24 UTC, dragonfly28 approved these changes
Alles drin und alles läuft!

2024-07-09 13:42 UTC, dragonfly28 approved these changes
Everything fine now! :smiley:

2024-07-09 13:43 UTC, merged