122 setup entwicklung für wls service vorfaelleundvorkommnisse
it-at-m/Wahllokalsystem pull request #364
Opened 2024-07-16 14:31 UTC by vjohnslhm

# Beschreibung:

Erstellung des Services Vorfälle und Vorkommnisse

## Definition of Done (DoD):

### Backend ###
- [ ] Doku aktualisiert
- [ ] Swagger-API vollständig
- [ ] Unit-Tests gepflegt
- [ ] Integrationstests gepflegt
- [ ] Beispiel-Requests gepflegt

# Referenzen[^1]:

Verwandt mit Issue #

Closes #122 

> [^1]: _Nicht zutreffende Referenzen vor dem Speichern entfernen_

2024-07-16 15:07 UTC, MrSebastian requested changes
Ein paar Stellen müssen noch angepasst werden aber ansonsten sieht es gut aus.

2024-07-16 15:07 UTC, MrSebastian commented on docs/src/features/vorfaelleundvorkommnisse-service/index.md
> +# Vorfälle und Vorkommnisse-Service
Die Beschreibung muss noch in der Sidebar verlinkt werden

2024-07-16 15:07 UTC, MrSebastian commented on docs/src/features/vorfaelleundvorkommnisse-service/index.md
> +Service zum erfassen und einsehen von Vorfällen und Vorkommnissen.
Ich bin mir nicht sicher ob bei `erfassen` und `einsehen` es sich um eine Substantivierung handelt und daher die Werben groß beginnen müssen.

2024-07-16 15:07 UTC, MrSebastian commented on wls-vorfaelleundvorkommnisse-service/src/main/resources/application-db-h2.yml
> +    url: jdbc:h2:mem:wls-auth-service
nicht der auth-service

2024-07-16 15:07 UTC, MrSebastian commented on wls-vorfaelleundvorkommnisse-service/src/main/resources/application-db-oracle.yml
> +    username: wls_auth_service
nicht der auth-service

2024-07-16 15:07 UTC, MrSebastian commented on wls-vorfaelleundvorkommnisse-service/src/main/resources/application-local.yml
> +  port: 39152
bitte nächsten freien Port verwenden. `39152` soll durch den Auth-Service verwendet werden.  Hintergrund dazu ist [dieser ADR](https://it-at-m.github.io/Wahllokalsystem/technik/adr/adr-improve-getting-started-of-services.html#entscheidung)

2024-07-16 15:07 UTC, MrSebastian commented on wls-vorfaelleundvorkommnisse-service/src/test/java/de/muenchen/oss/wahllokalsystem/vorfaelleundvorkommnisseservice/configuration/UnicodeConfigurationTest.java
> +    @Disabled
Hierfür bitte analog zu #201 ein Issue aufmachen damit wir nicht vergessen den und andere aktuell deaktivierte Tests zu aktivieren.

Die deaktivierten Tests setzen auf spring-data-rest welches wir entfernt haben. Und ohne vorhandene Controller gibt es keine Requests.

2024-07-16 15:07 UTC, MrSebastian commented on wls-vorfaelleundvorkommnisse-service/pom.xml
> +    <artifactId>wls-auth-service</artifactId>
muss noch angepasst werden

2024-07-16 15:07 UTC, MrSebastian commented on wls-vorfaelleundvorkommnisse-service/pom.xml
> +    <name>wls_auth_service</name>
muss noch angepasst werden

2024-07-16 16:01 UTC, vjohnslhm commented on wls-vorfaelleundvorkommnisse-service/src/test/java/de/muenchen/oss/wahllokalsystem/vorfaelleundvorkommnisseservice/configuration/UnicodeConfigurationTest.java
> +    @Disabled
#366

2024-07-17 10:51 UTC, MrSebastian approved these changes

2024-07-17 11:48 UTC, merged