155 implementierung wahlbeteiligung
it-at-m/Wahllokalsystem pull request #382
Opened 2024-07-22 15:03 UTC by dragonfly28

# Beschreibung:

Implementierung für Speichern der Wahlbeteiligung (WahlbeteiligungsMeldungDTO) in der DB.

## Definition of Done (DoD):

### Backend ###
- [x] Doku aktualisiert
- [x] Swagger-API vollständig
- [x] Unit-Tests gepflegt
- [x] Integrationstests gepflegt
- [x] Beispiel-Requests gepflegt

Closes #155

2024-07-23 14:27 UTC, MrSebastian requested changes

2024-07-23 14:27 UTC, MrSebastian commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/exception/ExceptionConstants.java
> +            MESSAGE_SAVEWAHLBETEILIGUNG_WAHLID_FEHLT);
Anstelle von deinen Codes und Messages könntest du die Codes `CODE_WAHLID_FEHLT` und `CODE_BEZIRKID_FEHLT` verwenden. Das Gleiche gilt für die Message.

2024-07-23 14:27 UTC, MrSebastian commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/exception/ExceptionConstants.java
> +    public static final String MESSAGE_SAVEWAHLBETEILIGUNG_MELDEZEITPUNKT_FEHLT = "Der Meldezeitpunkt fehlt";
Die Werte der Konstanten könntest du auch direkt im ExceptionDataWrapper verwenden.

2024-07-23 14:27 UTC, MrSebastian commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/service/wahlbeteiligung/WahlbeteiligungService.java
> +        log.debug("#saveWahlbeteiligung");
unnötige Leerzeile

```suggestion
    public void saveWahlbeteiligung(@P("wahlbeteiligungToSet") final WahlbeteiligungsMeldungDTO wahlbeteiligungToSet) {
        log.debug("#saveWahlbeteiligung");
```

2024-07-23 14:27 UTC, MrSebastian commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/service/wahlbeteiligung/WahlbeteiligungService.java
> +    }
unnötige Leerzeile

```suggestion
        wahlbeteiligungRepository.save(wahlbeteiligungMapper.toEntity(wahlbeteiligungToSet));
    }
```

2024-07-23 14:27 UTC, MrSebastian commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/service/wahlbeteiligung/WahlbeteiligungValidator.java
> +        if (wahlbeteiligungToSet.meldeZeitpunkt() == null || StringUtils.isBlank(wahlbeteiligungToSet.meldeZeitpunkt().toString())) {
wie kann `toString` ein Blank-String liefern? Wenn es nicht null ist muss es doch ein gültiger Zeitpunkt sein.

2024-07-23 14:27 UTC, MrSebastian commented on wls-eai-service/src/test/java/de/muenchen/oss/wahllokalsystem/eaiservice/rest/wahlbeteiligung/WahlbeteiligungControllerIntegrationTest.java
> +            Assertions.assertThat(savedWahlbeteiligung.getMeldeZeitpunkt()).isEqualTo(expectedSavedWahlbeteiligung.getMeldeZeitpunkt());
Du könntest auch `savedWahlbeteiligung` direkt mit `expectedSavedWahlbeteiligung` vergleichen wenn du `.usingRecursiveComparison().ignoringFields()` bei `Assertions` arbeitest.

Das hat meiner Meinung den Vorteil dass man bei Update am Datenmodell nicht vergessen kann den Test entsprechend zu aktualisieren.

2024-07-23 14:27 UTC, MrSebastian commented on wls-eai-service/src/test/java/de/muenchen/oss/wahllokalsystem/eaiservice/rest/wahlbeteiligung/WahlbeteiligungControllerTest.java
> +            val wahlbeteiligungsMeldungDTO = WahlbeteiligungsMeldungDTO.builder().build();
unnötige Leerzeile

```suggestion
        void serviceIsCalled() {
            val wahlbeteiligungsMeldungDTO = WahlbeteiligungsMeldungDTO.builder().build();
```

2024-07-23 14:27 UTC, MrSebastian commented on wls-eai-service/src/test/java/de/muenchen/oss/wahllokalsystem/eaiservice/rest/wahlbeteiligung/WahlbeteiligungControllerTest.java
> +    }
unnötige Leerzeile

```suggestion
        }
    }
```

2024-07-23 14:27 UTC, MrSebastian commented on wls-eai-service/src/test/java/de/muenchen/oss/wahllokalsystem/eaiservice/service/wahlbeteiligung/WahlbeteiligungMapperTest.java
> +            val id = UUID.randomUUID();
unused local variable

```suggestion
        void ofWahlbeteiligungsMeldungDTO() {
```

2024-07-23 14:27 UTC, MrSebastian commented on wls-eai-service/src/test/java/de/muenchen/oss/wahllokalsystem/eaiservice/service/wahlbeteiligung/WahlbeteiligungSecurityTest.java
> +        void accessDeniedOnServiceWithWrongAuthority() {
ich würde den Test eher ohne Rechte durchführen. Bei unsere Security gibt es streng genommen keine falsche Authority. Entweder man hat das Recht oder man es nicht. Die Nichtexistenz einer Berechtigung ist nicht von Relevanz.

2024-07-23 14:27 UTC, MrSebastian commented on wls-eai-service/src/test/java/de/muenchen/oss/wahllokalsystem/eaiservice/service/wahlbeteiligung/WahlbeteiligungServiceTest.java
> +    }
unnötige Leerzeile

```suggestion
        }
    }
```

2024-07-23 14:27 UTC, MrSebastian commented on wls-eai-service/src/test/java/de/muenchen/oss/wahllokalsystem/eaiservice/service/wahlbeteiligung/WahlbeteiligungValidatorTest.java
> +    class validDTOToSetOrThrow {
Bitte auch Tests ergänzen für den Fall dass `wahlID` und `wahlbezirkID` ein Leerstring oder Blankstring sind. Außerdem bitte einen Test ergänzen für den Fall dass `wahlbeteiligungToSet` `null` ist.

2024-07-23 14:27 UTC, MrSebastian commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/domain/wahlbeteiligung/WahlbeteiligungRepository.java
> +    <S extends Wahlbeteiligung> S save(S wahlbeteiligung);
Die Definition ist nicht notwendig da sie bereits aus dem CrudRepo kommt. Bei anderen Service haben wir es um die notwendigen Rechte zu definieren.

```suggestion
public interface WahlbeteiligungRepository extends CrudRepository<Wahlbeteiligung, UUID> {
```

2024-07-24 05:26 UTC, dragonfly28 commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/exception/ExceptionConstants.java
> +            MESSAGE_SAVEWAHLBETEILIGUNG_WAHLID_FEHLT);
resolved with 5b36db700e8743d9a4e6834cb6dc24e820012158

2024-07-24 05:26 UTC, dragonfly28 commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/exception/ExceptionConstants.java
> +    public static final String MESSAGE_SAVEWAHLBETEILIGUNG_MELDEZEITPUNKT_FEHLT = "Der Meldezeitpunkt fehlt";
resolved with 5b36db700e8743d9a4e6834cb6dc24e820012158

2024-07-24 05:34 UTC, dragonfly28 commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/service/wahlbeteiligung/WahlbeteiligungValidator.java
> +        if (wahlbeteiligungToSet.meldeZeitpunkt() == null || StringUtils.isBlank(wahlbeteiligungToSet.meldeZeitpunkt().toString())) {
resolved with ea40b284695b3736736f14ead996e87b4729a3d7

2024-07-24 06:03 UTC, dragonfly28 commented on wls-eai-service/src/test/java/de/muenchen/oss/wahllokalsystem/eaiservice/rest/wahlbeteiligung/WahlbeteiligungControllerIntegrationTest.java
> +            Assertions.assertThat(savedWahlbeteiligung.getMeldeZeitpunkt()).isEqualTo(expectedSavedWahlbeteiligung.getMeldeZeitpunkt());
resolved with a7d034a96dcaa5ceaecd2a4be4085476c30aa66c

2024-07-24 06:04 UTC, dragonfly28 commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/service/wahlbeteiligung/WahlbeteiligungService.java
> +        log.debug("#saveWahlbeteiligung");
resolved with f264be932ab9019f887dbae4ed9c06debd3024f5

2024-07-24 06:04 UTC, dragonfly28 commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/service/wahlbeteiligung/WahlbeteiligungService.java
> +    }
resolved with f264be932ab9019f887dbae4ed9c06debd3024f5

2024-07-24 06:04 UTC, dragonfly28 commented on wls-eai-service/src/test/java/de/muenchen/oss/wahllokalsystem/eaiservice/rest/wahlbeteiligung/WahlbeteiligungControllerTest.java
> +            val wahlbeteiligungsMeldungDTO = WahlbeteiligungsMeldungDTO.builder().build();
resolved with f264be932ab9019f887dbae4ed9c06debd3024f5

2024-07-24 06:04 UTC, dragonfly28 commented on wls-eai-service/src/test/java/de/muenchen/oss/wahllokalsystem/eaiservice/rest/wahlbeteiligung/WahlbeteiligungControllerTest.java
> +    }
resolved with f264be932ab9019f887dbae4ed9c06debd3024f5

2024-07-24 06:05 UTC, dragonfly28 commented on wls-eai-service/src/test/java/de/muenchen/oss/wahllokalsystem/eaiservice/service/wahlbeteiligung/WahlbeteiligungServiceTest.java
> +    }
resolved with f264be932ab9019f887dbae4ed9c06debd3024f5

2024-07-24 06:15 UTC, dragonfly28 commented on wls-eai-service/src/test/java/de/muenchen/oss/wahllokalsystem/eaiservice/service/wahlbeteiligung/WahlbeteiligungSecurityTest.java
> +        void accessDeniedOnServiceWithWrongAuthority() {
resolved with b84a71b0cd6ca71be0ae45e637029accbb34559e

2024-07-24 06:56 UTC, dragonfly28 commented on wls-eai-service/src/test/java/de/muenchen/oss/wahllokalsystem/eaiservice/service/wahlbeteiligung/WahlbeteiligungValidatorTest.java
> +    class validDTOToSetOrThrow {
resolved with fa4941cc904022b3638912dc4917b99408bbe8be

2024-07-24 07:42 UTC, MrSebastian approved these changes

2024-07-24 07:57 UTC, merged