Templates für Pull-Requests in Frontend- und Backendprojekte sowie fü…
it-at-m/Wahllokalsystem pull request #41
Opened 2024-03-19 15:51 UTC by Nic12345678

### Beschreibung:

Hiemit wurden die Templates für Pull-Requests für Frontend Backend und Dokumentation umgesetzt.

### Definition of Done (DoD):

[X] Links geprüft

### Referenzen[^1]:

Closes #37

> [^1]: _Nicht zutreffende Referenzen vor dem Speichern entfernen_

2024-03-19 17:54 UTC, MrSebastian requested changes, later dismissed
Die Idee mit der Fußnote gefällt mir 👍 

---

Ich habe das mit dem Template in einem anderen Projekt ausprobiert und glaube es funktioniert nicht wie gewollt. Eine Vorlage konnte ich nur über Query-Parameter auswählen. Im PR-UI habe ich nichts dazu gesehen.

2024-03-19 17:54 UTC, MrSebastian commented on .github/PULL_REQUEST_TEMPLATE/backend_pull_request_template.md
> +[ ] Doku aktualisiert
Die MD-Syntax für Tasks ist eine Andere

```suggestion
- [ ] Doku aktualisiert
- [ ] Swagger-API vollständig
- [ ] Unit-Tests gepflegt
- [ ] Integrationstests gepflegt
- [ ] Beispiel-Requests gepflegt
- [ ] Doku aktualisiert
```

2024-03-19 17:54 UTC, MrSebastian commented on .github/PULL_REQUEST_TEMPLATE/dokumentation_pull_request_template.md
> +[ ] Links geprüft
Die MD-Syntax für Tasks ist eine Andere

```suggestion
- [ ] Links geprüft
```

2024-03-19 17:54 UTC, MrSebastian commented on .github/PULL_REQUEST_TEMPLATE/frontend_pull_request_template.md
> +[ ] Komponententests gepflegt
Die MD-Syntax für Tasks ist eine Andere

```suggestion
- [ ] Doku aktualisiert
- [ ] Unit-Tests gepflegt
- [ ] Komponententests gepflegt
```

2024-04-03 07:55 UTC, MrSebastian commented
> Die Idee mit der Fußnote gefällt mir 👍
> 
> Ich habe das mit dem Template in einem anderen Projekt ausprobiert und glaube es funktioniert nicht wie gewollt. Eine Vorlage konnte ich nur über Query-Parameter auswählen. Im PR-UI habe ich nichts dazu gesehen.


Vorschlag: Zusammenführen in einer Datei und beim Erstellen werden 2 von 3 Bereichen entfernt

2024-04-04 08:14 UTC, MrSebastian commented
> > Die Idee mit der Fußnote gefällt mir 👍
> > Ich habe das mit dem Template in einem anderen Projekt ausprobiert und glaube es funktioniert nicht wie gewollt. Eine Vorlage konnte ich nur über Query-Parameter auswählen. Im PR-UI habe ich nichts dazu gesehen.
> 
> Vorschlag: Zusammenführen in einer Datei und beim Erstellen werden 2 von 3 Bereichen entfernt

angenommen

2024-04-04 13:32 UTC, dragonfly28 approved these changes

2024-04-04 13:35 UTC, merged