403 entfernung von unnötigen leerzeilen zu beginn einer methode
it-at-m/Wahllokalsystem pull request #417
Opened 2024-09-16 13:50 UTC by dragonfly28

# Beschreibung:

* regexp angepasst damit auch private methods erfasst werden
* alle Leerzeilen nach Methodenstart entfernt
* alle checkstyle.xml Konfigurationen in den Projekten angepasst

## Definition of Done (DoD):

Closes #403

> [^1]: _Nicht zutreffende Referenzen vor dem Speichern entfernen_

2024-09-17 14:39 UTC, MrSebastian requested changes

2024-09-17 14:39 UTC, MrSebastian commented on wls-wahlvorbereitung-service/src/main/java/de/muenchen/oss/wahllokalsystem/wahlvorbereitungservice/rest/urnenwahlvorbereitung/UrnenwahlvorbereitungWriteDTO.java
> -
Das verschlechter aus meiner Sicht die Lesbarkeit.

Eine Leerzeile nach einer Klassendefinition ist von Vorteil.

2024-09-23 15:34 UTC, MrSebastian requested changes
Da wir von Änderungen an den checkstyle.xml-Files Abstand genommen haben, bitte die Files komplett reverten.

2024-09-23 15:35 UTC, MrSebastian commented
Und bitte auch die PR-Beschreibung aktualisieren

2024-09-24 14:34 UTC, dragonfly28 commented
- revert der commits bei checkstyle.xml 
- PR-Beschreibung aktualisiert

2024-09-25 05:55 UTC, MrSebastian approved these changes

2024-09-25 07:13 UTC, merged