214 eai implementierung ergebnismeldung
it-at-m/Wahllokalsystem pull request #422
Opened 2024-09-19 10:56 UTC by GerhardPx

# Beschreibung:

Implementierung der Ergebnismeldung in der EAI

## Definition of Done (DoD):

### Backend ###
- [x] Doku aktualisiert
- [ ] Swagger-API vollständig
- [x] Unit-Tests gepflegt
- [x] Integrationstests gepflegt
- [x] Beispiel-Requests gepflegt

### Dokumentation
- [x] Links geprüft

Closes #214

2024-09-23 10:20 UTC, MrSebastian requested changes

2024-09-23 10:20 UTC, MrSebastian commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/domain/ergebnismeldung/AWerte.java
> +    @Column(name = "a1")
```suggestion
```

2024-09-23 10:20 UTC, MrSebastian commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/domain/ergebnismeldung/AWerte.java
> +    @Column(name = "a2")
```suggestion
```

2024-09-23 10:20 UTC, MrSebastian commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/domain/ergebnismeldung/BWerte.java
> +    @Column(name = "b")
```suggestion
```

2024-09-23 10:20 UTC, MrSebastian commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/domain/ergebnismeldung/BWerte.java
> +    @Column(name = "b1")
```suggestion
```

2024-09-23 10:20 UTC, MrSebastian commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/domain/ergebnismeldung/BWerte.java
> +    @Column(name = "b2")
```suggestion
```

2024-09-23 10:20 UTC, MrSebastian commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/domain/ergebnismeldung/Ergebnis.java
> +@EqualsAndHashCode
Ist Teil von `@Data`

```suggestion
```

2024-09-23 10:20 UTC, MrSebastian commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/domain/ergebnismeldung/Ergebnis.java
> +public class Ergebnis {
Vorschlag: mit der Implementierung werden n-Ergebnismeldungen gespeichert was auch aktuell ausreichend ist. Leider ist so nicht erkennbar wann welches Ergebnis kam. Wenn du eine Spalte für den Timestamp ergänzt mit dem Erstellungszeitpunkt könnte man so die Reihenfolge sehen: https://www.baeldung.com/hibernate-creationtimestamp-updatetimestamp

2024-09-23 10:20 UTC, MrSebastian commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/domain/ergebnismeldung/WahlbriefeWerte.java
> +    @Column(name = "zurueckgewiesenGesamt")
```suggestion
```

2024-09-23 10:20 UTC, MrSebastian commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/rest/ergebnismeldung/ErgebnismeldungController.java
> +public class ErgebnismeldungController {
warum einen 2. Controller?

2024-09-23 10:20 UTC, MrSebastian commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/rest/wahlergebnis/dto/ErgebnismeldungDTO.java
> +                                 Set<UngueltigeStimmzettelDTO> ungueltigeStimmzettels,
aus Interesse: was war der Hintergrund für Wechsel von `List` auf `Set`

2024-09-23 10:20 UTC, MrSebastian commented on wls-eai-service/src/test/java/de/muenchen/oss/wahllokalsystem/eaiservice/rest/ergebnismeldung/ErgebnismeldungControllerIntegrationTest.java
> +            val requestBody = getErgebnismeldungDTO();
```suggestion
        void meldungIsSaved() throws Exception {
            val requestBody = getErgebnismeldungDTO();
```

2024-09-23 10:20 UTC, MrSebastian commented on wls-eai-service/src/test/java/de/muenchen/oss/wahllokalsystem/eaiservice/rest/ergebnismeldung/ErgebnismeldungControllerIntegrationTest.java
> +            val ergebnisse2 = getErgebnis();
würde ich zusammen mit der Erstellung von `expectedSavedErgebnismeldung` später in eine Methode kapseln damit die Erstellung der Expectedwerte zusammen sind

2024-09-23 10:20 UTC, MrSebastian commented on wls-eai-service/src/test/java/de/muenchen/oss/wahllokalsystem/eaiservice/rest/ergebnismeldung/ErgebnismeldungControllerIntegrationTest.java
> +            val requestBody = getErgebnismeldungDTO();
```suggestion
        void validationExceptionOccurredAndIsMapped() throws Exception {
            val requestBody = getErgebnismeldungDTO();
```

2024-09-23 10:20 UTC, MrSebastian commented on wls-eai-service/src/test/java/de/muenchen/oss/wahllokalsystem/eaiservice/service/ergebnismeldung/ErgebnismeldungMapperTest.java
> +            val aWerte2 = new AWerte();
anstelle von `2` wäre `expected` als Prefix besser.

2024-09-23 10:20 UTC, MrSebastian commented on wls-eai-service/src/test/java/de/muenchen/oss/wahllokalsystem/eaiservice/service/ergebnismeldung/ErgebnismeldungServiceSecurityTest.java
> +            val ergebnismeldungToSave = ErgebnismeldungDTO.builder().wahlbezirkID("00000000-0000-0000-0000-000000000001").wahlID("wahlID1").meldungsart(null)
Wenn du `null` für die einzelnen Parameter mitgibst kannst du den Aufruf auch weglassen. Es greift dann der der Default, der `null` ist, sofern nichts anderes definiert wurde mit `@Builder.Default`.

Trifft auch auf andere Klassen zu.

2024-09-23 10:20 UTC, MrSebastian commented on wls-eai-service/src/test/java/de/muenchen/oss/wahllokalsystem/eaiservice/service/ergebnismeldung/ErgebnismeldungServiceSecurityTest.java
> +            val ergebnismeldungToSave = ErgebnismeldungDTO.builder().wahlbezirkID("00000000-0000-0000-0000-000000000001").wahlID("wahlID1").meldungsart(null)
Wenn du `null` für die einzelnen Parameter mitgibst kannst du den Aufruf auch weglassen. Es greift dann der der Default, der `null` ist, sofern nichts anderes definiert wurde mit `@Builder.Default`.

Trifft auch auf andere Klassen zu.

2024-09-23 10:20 UTC, MrSebastian commented on wls-eai-service/src/test/java/de/muenchen/oss/wahllokalsystem/eaiservice/service/ergebnismeldung/ErgebnismeldungValidatorTest.java
> +        void exceptionWhenWahlbezirkIDIsBlank() {
Blank muss sich auf 3 Fälle aufteilen
- null
- ""
- "   "

2024-09-23 10:20 UTC, MrSebastian commented on wls-eai-service/src/test/java/de/muenchen/oss/wahllokalsystem/eaiservice/service/ergebnismeldung/ErgebnismeldungValidatorTest.java
> +        void exceptionWhenWahlIDIsBlank() {
Blank muss sich auf 3 Fälle aufteilen
- null
- ""
- "   "

2024-09-23 10:20 UTC, MrSebastian commented on wls-eai-service/src/test/resources/httpRequests/ergebnismeldung.http
> +}
Bitte `aWerte`, `bWerte` sowie die Arrays vollständig belegen. Bei den Arrays sollten auch mehrere Objekte enthalten sein.

2024-09-25 11:56 UTC, GerhardPx commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/rest/ergebnismeldung/ErgebnismeldungController.java
> +public class ErgebnismeldungController {
ahem Controller angelegt und nicht gesehen dass bereits einer mit anderem Namen als der Datentyp angelegt wurde 😂 
kommt raus

2024-09-25 11:56 UTC, GerhardPx commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/rest/wahlergebnis/dto/ErgebnismeldungDTO.java
> +                                 Set<UngueltigeStimmzettelDTO> ungueltigeStimmzettels,
Einheitlichkeit

2024-09-25 12:36 UTC, MrSebastian commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/rest/wahlergebnis/dto/ErgebnismeldungDTO.java
> +                                 Set<UngueltigeStimmzettelDTO> ungueltigeStimmzettels,
Verstehe. Mit Blick auf die aktuelle Funktionalität sehe ich darin kein Problem. Wenn die Reihenfolge mal Relevant wird müssen wir auf `List` umstellen.

2024-09-25 14:27 UTC, GerhardPx commented on wls-eai-service/src/test/java/de/muenchen/oss/wahllokalsystem/eaiservice/service/ergebnismeldung/ErgebnismeldungMapperTest.java
> +            val aWerte2 = new AWerte();
Actually find ich die Anmerkung so gut dass ich das durch den ganzen Test ziehe

2024-09-30 12:09 UTC, GerhardPx commented on wls-eai-service/src/test/java/de/muenchen/oss/wahllokalsystem/eaiservice/rest/ergebnismeldung/ErgebnismeldungControllerIntegrationTest.java
> +            val ergebnisse2 = getErgebnis();
das habe ich nicht genau verstanden. Was genau würdest du kapseln und warum?

2024-09-30 15:02 UTC, MrSebastian commented on wls-eai-service/src/test/java/de/muenchen/oss/wahllokalsystem/eaiservice/rest/ergebnismeldung/ErgebnismeldungControllerIntegrationTest.java
> +            val ergebnisse2 = getErgebnis();
ab Zeile 103 erstellst du das `expectedSavedErgebnismeldung`  womit der Ist-Wert verglichen wird. Die Zeile 83 bis 96 erzeugen Daten für dieses Objekte auf Zeile 103. Ich finde es liegt eine Verteilung vor wenn es um die expectedWerte geht, da dazwischen ein findAll und ein Assert geschieht. Es lesbarer wenn die beiden Blöcke zusammen wären. Und da der Block größer ist dachte ich könnte eine zusätzliche Methode den Test lesbarer machen wenn die ExpectedDaten in einer eigenen Methode erzeugt werden.

2024-10-02 13:29 UTC, MrSebastian requested changes

2024-10-02 13:29 UTC, MrSebastian commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/service/ergebnismeldung/ErgebnismeldungMapper.java
> +    Ergebnis toEntity(ErgebnisDTO dto);
Mapstruct findet es anhand des Namens zusammen

```suggestion
    Ergebnismeldung toEntity(ErgebnismeldungDTO dto);

    @Mapping(target = "erstellungszeit", ignore = true)
    Ergebnis toEntity(ErgebnisDTO dto);
```

2024-10-02 13:29 UTC, MrSebastian commented on wls-eai-service/src/main/java/de/muenchen/oss/wahllokalsystem/eaiservice/domain/ergebnismeldung/Ergebnis.java
> +    @CreationTimestamp
richtige Lösung, ist aber an der Meldung besser aufgehoben, da es Ergebnisse ohne Meldung nicht gibt und Ergebnisse nicht unabhängig von der Meldung erstellt werden.

2024-10-02 13:29 UTC, MrSebastian commented on wls-eai-service/src/test/resources/httpRequests/ergebnismeldung.http
>    "aWerte": {
bitte in dem Request auch noch a2, b, b2 mit aufnehmen. Muss **nicht** in die Failed requests rein

2024-10-02 14:41 UTC, MrSebastian approved these changes

2024-10-02 14:42 UTC, merged