141 fix wahlen können gelesen und geschrieben werden
it-at-m/Wahllokalsystem pull request #423
Opened 2024-09-20 10:44 UTC by Nic12345678

# Beschreibung:

Anlass diese Fix-Issues war, dass im Rahmen des Demo-termins für #141 wir feststellten, dass zwar zuerst die Wahlen vom Remote gelesen und ins Repo geschrieben wurden, aber nach dem Post-Wahlen mit Wahlen mit den gleichen WahlIDs
 wie die davor gespeicherten, ein erneutes GetWahlen wieder die alten Wahlen zurück lieferte als die neulich gespeicherten.

Dies wäre ein Fehler gewesen.

# Ergebnis der Analyse

Unsere Schlussfolgerung war ein Trugschluss. Wir haben dabei übersehen, dass die zuletzt gespeicherten Wahlen, die wir als Antwort erwartet hätten, einen anderen "wahltag" also ein anderes Wahltagdatum hatten, als das Datum des Wahltages dessen ID wir im letzten getWahlen(wahltagID) als Abfrageparameter sandten. Somit war im Service nichts im Repo für den WahltagID gefunden und erneut vom Remote-Client geladen.

## Durchgeführte Korrekturen

Tests wurden ergänzt und im http-wahlen File ein Kommentar eingetragen

2024-09-25 12:23 UTC, MrSebastian requested changes
Damit wir uns in Phase 3 die API noch einmal ansehen habe ich ein Issue erstellt: #441

2024-09-25 12:23 UTC, MrSebastian commented on wls-basisdaten-service/src/test/resources/wahlen.http
> +    "wahltag": "2024-07-20",
Dann werden die Daten so überschrieben dass sie auch wieder lesbar sind. Der Wahltag sollte auch bei den anderen Wahlen entsprechend angepasst werden. Dann kann der Hinweis auch verkürzt werden und mitteilen dass wir der Wahltag entsprechend Import gesetzt sein muss.

```suggestion
    "wahltag": "2024-07-25",
```

2024-09-25 12:23 UTC, MrSebastian commented on wls-basisdaten-service/src/test/java/de/muenchen/oss/wahllokalsystem/basisdatenservice/rest/wahlen/WahlenControllerIntegrationTest.java
> +            val request_first = MockMvcRequestBuilders.post("/businessActions/wahlen/" + searchingForWahltag.getWahltagID()).with(csrf())
Für die Einheitlichkeit wäre `requestFirst` besser. Noch besser wäre wenn man aus dem Namen erkennt dass es sich um die Wahlen für eine WahltagID handelt.

2024-09-25 12:23 UTC, MrSebastian commented on wls-basisdaten-service/src/test/java/de/muenchen/oss/wahllokalsystem/basisdatenservice/services/wahlen/WahlenServiceTest.java
> +        void postingNewWahlenOverridesExistingWithSameId() {
anstelle von first und second würde ich eher Begriffe wie old, overrideable, overriding, new, replacing, ... verwenden

2024-09-27 08:31 UTC, Nic12345678 commented on wls-basisdaten-service/src/test/resources/wahlen.http
> +    "wahltag": "2024-07-20",
Die Ursache, warum ich aus der "06" eine "20" gemacht habe und du aus der "20" eine "25" suggerierst, ist, dass der DummyClient Wahlen mit dem Datum des Tages der Testausführung liefert :) während der http-Test ein POST mit Wahlen mit hartcodiertem Datum macht. Ich werde es vereinheitlichen.

2024-09-27 10:08 UTC, Nic12345678 commented on wls-basisdaten-service/src/test/resources/wahlen.http
> +    "wahltag": "2024-07-20",
Siehe hier fe5e5da2acfacc759f2fdf9d18e8d74d575e12f0

2024-09-27 10:20 UTC, Nic12345678 commented on wls-basisdaten-service/src/test/java/de/muenchen/oss/wahllokalsystem/basisdatenservice/rest/wahlen/WahlenControllerIntegrationTest.java
> +            val request_first = MockMvcRequestBuilders.post("/businessActions/wahlen/" + searchingForWahltag.getWahltagID()).with(csrf())
„Der Bessere ist der Feind des Guten . “ - Voltaire :) 
Ich bleibe beim `requestFirst` und `requestSecond`, denn das mit der wahltagID zu suggerioeren im Namen würde zu einem zu langem Namen führen: z.Bsp. `requestFirstForSameWahltagID`.
Resolved hier: 3855fc29e8570c65617ac6314d64733425f797c7

2024-09-27 10:27 UTC, Nic12345678 commented on wls-basisdaten-service/src/test/java/de/muenchen/oss/wahllokalsystem/basisdatenservice/services/wahlen/WahlenServiceTest.java
> +        void postingNewWahlenOverridesExistingWithSameId() {
Es muss nicht heißen, dass die zuerst gespeicherten "Old" sind, denn nicht alle werden zwangsweise überschrieben, sondern nur diejenigen mit der gleichen ID wie die neu gespeicherten. Ich habe sie aber CamelCase geschrieben.

Resolved: 688e707c7f0d570829f77031418f6172b0d37a8c

2024-09-30 06:28 UTC, MrSebastian approved these changes

2024-09-30 07:58 UTC, merged