Domain Elemente in eigenen Packages oder in common package eingeteilt
it-at-m/Wahllokalsystem pull request #448
Opened 2024-09-27 13:55 UTC by Nic12345678

# Beschreibung:

Unter "domain" habe ich für die Elemente die keinem anderen Subpackage untergeordnet waren, die Packages "common", "wahlvorschlaege", "wahlbezirk", "ungueltigewahlscheine", "handbuch" eingerichtet und die entsprechenden Elemente wie im Issue gewünscht eingeteilt. Außerdem ergab sich die Notwendigkeit das Package "wahlbezirke" unter "rest" einzuführen.

Unter "tests/domain" gibt es nur 4 RepositoryTests - eine Sub-Package Aufsplittung, würde bedeuten, 4 Sub-Packages mit jeweils einer TestKlasse. Das habe ich erst einmal so gelassen.

## Definition of Done (DoD):

### Backend ###
- [X] Applikation nach einem clean fehlerfrei gestartet
- [X] Unit Tests erfolgreich gelaufen

# Referenzen[^1]:

Closes #383

2024-10-01 09:01 UTC, dragonfly28 commented
Neben den Anmerkungen zum geänderten Code ist mir noch aufgefallen, dass die packages unter ```domain``` und ```rest``` zum Teil unterschiedlich heissen:
- ```domain.wahl``` <-> ```rest.wahlen```
- ```domain.wahlbezirk``` <-> ```rest.wahlbezirke```
- ```domain.wahltag``` fehlt <-> ```rest.wahltage```
- ```domain.wahlvorschlaege``` <-> ```rest.wahlvorschlag```

Die sollten gleich heissen um Verwirrung zu vermeiden. Genauso auch in den test-packages.

2024-10-01 09:02 UTC, dragonfly28 requested changes

2024-10-01 09:02 UTC, dragonfly28 commented on wls-basisdaten-service/src/main/java/de/muenchen/oss/wahllokalsystem/basisdatenservice/domain/common/Wahltag.java
Sollte der ```Wahltag``` und das ```WahltagRepository``` nicht auch in ein eigenes package ```wahltag```?

2024-10-01 09:02 UTC, dragonfly28 commented on wls-basisdaten-service/src/main/java/de/muenchen/oss/wahllokalsystem/basisdatenservice/domain/common/WahltagRepository.java
Sollte der ```Wahltag``` und das ```WahltagRepository``` nicht auch in ein eigenes package ```wahltag```?

2024-10-01 09:02 UTC, dragonfly28 commented on wls-basisdaten-service/src/main/java/de/muenchen/oss/wahllokalsystem/basisdatenservice/rest/wahlbezirke/WahlbezirkDTO.java
Der package-Name müsste in der Einzahl ```wahlbezirk``` heissen und nicht ```wahlbezirke``` - sonst passt es nicht zu den Package-Namen unter domain

2024-10-01 12:55 UTC, Nic12345678 commented on wls-basisdaten-service/src/main/java/de/muenchen/oss/wahllokalsystem/basisdatenservice/domain/common/Wahltag.java
Im Issue steht "Klassen, die aus mehreren subpackages referenziert werden sollen ins subpackage common"
siehe #383

2024-10-01 12:56 UTC, Nic12345678 commented on wls-basisdaten-service/src/main/java/de/muenchen/oss/wahllokalsystem/basisdatenservice/domain/common/WahltagRepository.java
Im Issue steht "Klassen, die aus mehreren subpackages referenziert werden sollen ins subpackage common"
siehe #383

2024-10-01 13:21 UTC, Nic12345678 commented on wls-basisdaten-service/src/main/java/de/muenchen/oss/wahllokalsystem/basisdatenservice/rest/wahlbezirke/WahlbezirkDTO.java
Die Packages unter "domain" sind nah an der Datenbankschicht und ihre Bezeichnung orientiert sich an 2 Regeln:

1. Grundsätzlich wird eine Datenbanktabelle im Singular benannt. Z.Bsp. Tabelle Person enthält mehrere Einträge / Zeilen, jede von dieser Zeile beschreibt ein Person-Objekt;
2. Falls unter der gleichen Domäne, mehrere Tabellen existieren mit hierarchischen Beziehungen, trägt die Bezeichnung der Domäne den Namen der obersten Struktur. Wenn diese eine Bezeichnung hat die im Plural formuliert ist, dann trägt auch die Domäne diese Bezeichnung - siehe "`Wahlvorschlaege`" oder "`UngueltigeWahlscheine`". Die Tabelle "Wahlvorschlaege" enthält mehrere Zeilen, jede Zeile beschreibt eine Gruppe von "Wahlvorschläge".

Das wäre der Hintergedanke, die Begründung, warum die eine Domäne (ein domain.package) eine Plural Formulierung hat und die andere nicht. Domäne Wahlvorschlaege hat eine Tabelle die heißt "Wahlvorschlaege" und ist die oberste in der Hierarchie der Domäne. Eine Tabelle "Wahlbezirke" gibt es nicht, es gibt nur "Wahlbezirk".

Bei den Bezeichnungen der Packages, das gleiche, nur ohne Bezug auf Tabellen sondern auf die Operation die ein Rest-Controller ermöglicht und zwar falls mehrere Operationen, wird diejenige die "größte" Operation umfasst namensgebend für den Rest-Controller und auch für das Package. Im `WahlbezirkeController` gibt es nur die Methode/Operation "getWahlbezirke", es gibt keine "getWahlbezirk" Methode. Wenn man dort getWahlbezirke ausführt, dann ist dieser Controller für Wahlbezirke (pl.) verantwortlich, damit auch das Package im Plural. Gleiches bei domain.wahl und rest.wahlen.

Ich möchte das nicht so imponieren, aber wollte sagen, dass die Bezeichnungen nicht versehentlich so vergeben wurden, sondern aus den oben erwähnten Gründen.

2024-10-01 13:26 UTC, Nic12345678 commented on wls-basisdaten-service/src/main/java/de/muenchen/oss/wahllokalsystem/basisdatenservice/rest/wahlbezirke/WahlbezirkDTO.java
Wenn wir sagen, wir benennen alle Packages im Singular, und von der oberen Semantik z. Bsp. beim Controller der Wahlbezirke liefert aber auf "Wahlbezirk" endet absehen, habe ich nichts dagegen. Vllt. bereden wir das morgen kurz im Daily.

2024-10-02 07:54 UTC, dragonfly28 commented on wls-basisdaten-service/src/main/java/de/muenchen/oss/wahllokalsystem/basisdatenservice/domain/common/Wahltag.java
So wie ich das sehe wird der Wahltag nur im WahltagRepository und in einigen Tests verwendet, aber aus keiner Klasse in einem anderen package unter ```domain```, oder?
Ich dachte dass unter common nur Klassen wie z.B. ```domain.common.WahltagIdUndWahlbezirksart``` kommen, diese wird z.B. von ```domain.handbuch.Handbuch``` UND ```domain.ungueltigewahlscheine.UngueltigeWahlscheine``` referenziert.

2024-10-02 07:55 UTC, dragonfly28 commented on wls-basisdaten-service/src/main/java/de/muenchen/oss/wahllokalsystem/basisdatenservice/domain/common/WahltagRepository.java
dito

2024-10-02 13:21 UTC, dragonfly28 commented on wls-basisdaten-service/src/main/java/de/muenchen/oss/wahllokalsystem/basisdatenservice/rest/wahlbezirke/WahlbezirkDTO.java
Wie besprochen @Nic12345678 @MrSebastian :
- wichtig sind gleiche package-Namen unter domain/rest/services
- refactoring vorrangig unter package domain
- derzeit kein Fokus auf Singular/Plural-Refactoring

2024-10-04 07:13 UTC, Nic12345678 commented on wls-basisdaten-service/src/main/java/de/muenchen/oss/wahllokalsystem/basisdatenservice/domain/common/Wahltag.java
Wahltag-Objekte in wahltag-package verschoben

2024-10-04 07:14 UTC, Nic12345678 commented on wls-basisdaten-service/src/main/java/de/muenchen/oss/wahllokalsystem/basisdatenservice/rest/wahlbezirke/WahlbezirkDTO.java
resolved hier: d3090a0608d4057a85c4da104f6e665f2d18f868

2024-10-04 09:41 UTC, dragonfly28 approved these changes
Passt alles jetzt aus meiner Sicht.

2024-10-04 10:54 UTC, merged