169 implementierung monitoring wahlbeteiligung
it-at-m/Wahllokalsystem pull request #509
Opened 2024-10-21 14:40 UTC by dragonfly28

# Beschreibung:

* Implementierung Controller -> Service -> Repo + EAI-Zugriff für Meldung der Wahlbeteiligung (Waehleranzahl)

## Definition of Done (DoD):

### Backend ###
- [x] Doku aktualisiert
- [x] Swagger-API vollständig
- [x] Unit-Tests gepflegt
- [x] Integrationstests gepflegt
- [x] Beispiel-Requests gepflegt

Closes #169

2024-10-22 18:22 UTC, MrSebastian requested changes
bitte `val` verwenden anstatt mal `val` und mal `final` verwenden

2024-10-22 18:22 UTC, MrSebastian commented on stack/keycloak/migration/create-group-all-monitoring-authorities.yml
> +      user: wls_all
bitte den anderen `wls_all`-Usern auch die Gruppe zuordnen

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/main/java/de/muenchen/oss/wahllokalsystem/monitoringservice/MicroServiceApplication.java
> +                "de.muenchen.oss.wahllokalsystem.wls.common.security"
warum der Scan in `security`?

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/main/java/de/muenchen/oss/wahllokalsystem/monitoringservice/domain/waehleranzahl/Waehleranzahl.java
> +    private java.time.LocalDateTime uhrzeit;
Bitte importieren und nicht den absoluten Classnamen verwenden.

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/main/java/de/muenchen/oss/wahllokalsystem/monitoringservice/service/waehleranzahl/WaehleranzahlValidator.java
> +    }
Wird nicht verwendet.

```suggestion
```

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/main/java/de/muenchen/oss/wahllokalsystem/monitoringservice/service/waehleranzahl/WaehleranzahlValidator.java
> +    public void validWahlIdUndWahlbezirkIDOrThrow(final BezirkUndWahlID bezirkUndWahlID) {
es  fehlen Tests

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/main/resources/application.yml
> +      basePath: http://localhost:39146
die EAI sollte laut #352 auf `39149` sein

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/main/java/de/muenchen/oss/wahllokalsystem/monitoringservice/exception/ExceptionConstants.java
> +    public static ExceptionDataWrapper GETWAHLBETEILIGUNG_KEINE_DATEN = new ExceptionDataWrapper("302", "Die Wahlbeteiligung konnte nicht geladen werden.");
wird nicht verwendet

```suggestion
```

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/main/java/de/muenchen/oss/wahllokalsystem/monitoringservice/domain/waehleranzahl/Waehleranzahl.java
> +public class Waehleranzahl {
```suggestion
@AllArgsConstructor
public class Waehleranzahl {
```

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/main/java/de/muenchen/oss/wahllokalsystem/monitoringservice/domain/waehleranzahl/Waehleranzahl.java
> +@Embeddable
```suggestion
```

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/main/java/de/muenchen/oss/wahllokalsystem/monitoringservice/configuration/BasePathConfiguration.java
> +    private final de.muenchen.oss.wahllokalsystem.monitoringservice.eai.aou.ApiClient eaiApiClient;
Bitte Import verwenden

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/main/java/de/muenchen/oss/wahllokalsystem/monitoringservice/client/waehleranzahl/WaehleranzahlClientImpl.java
> +            throw exceptionFactory.createTechnischeWlsException(ExceptionConstants.FAILED_COMMUNICATION_WITH_EAI);
in der alten Anwendung wird die Exception nur geloggt und nicht weiter geworfen

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/main/java/de/muenchen/oss/wahllokalsystem/monitoringservice/client/waehleranzahl/WaehleranzahlClientImpl.java
> +    public void postWahlbeteiligung(WaehleranzahlModel waehleranzahlModel) throws WlsException {
```suggestion
    public void postWahlbeteiligung(final WaehleranzahlModel waehleranzahlModel) throws WlsException {
```

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/main/java/de/muenchen/oss/wahllokalsystem/monitoringservice/rest/waehleranzahl/WaehleranzahlController.java
> +    public void postWahlbeteiligung(@PathVariable("wahlbezirkID") String wahlbezirkID, @PathVariable("wahlID") String wahlID,
```suggestion
    public void postWahlbeteiligung(@PathVariable("wahlbezirkID") final String wahlbezirkID, @PathVariable("wahlID") final String wahlID,
```

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/main/java/de/muenchen/oss/wahllokalsystem/monitoringservice/rest/waehleranzahl/WaehleranzahlController.java
> +    ResponseEntity<WaehleranzahlDTO> getWahlbeteiligung(@PathVariable("wahlID") String wahlID, @PathVariable("wahlbezirkID") String wahlbezirkID) {
```suggestion
    ResponseEntity<WaehleranzahlDTO> getWahlbeteiligung(@PathVariable("wahlID") final String wahlID, @PathVariable("wahlbezirkID") final String wahlbezirkID) {
```

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/main/java/de/muenchen/oss/wahllokalsystem/monitoringservice/rest/waehleranzahl/WaehleranzahlDTO.java
> +    @NotNull String wahlbezirkID,
Die beiden Werte kommen über die Pfadvariablen, daher sollten sie nicht in das DTO.

Eine Streichung behält die Kompatibilität bei da es zu keinem Fehler kommt wenn die Daten übermittelt werden oder im Widerspruch zu den Pfadvariablen stehen.

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/main/java/de/muenchen/oss/wahllokalsystem/monitoringservice/service/waehleranzahl/WaehleranzahlModel.java
> +    @NotNull Long anzahlWaehler,
Sollte `long` sein (wie im Altsystem).

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/main/java/de/muenchen/oss/wahllokalsystem/monitoringservice/rest/waehleranzahl/WaehleranzahlDTO.java
> +    @NotNull Long anzahlWaehler,
Wenn auch hier `long` verwendet wird muss `@Schema(requiredMode = Schema.RequiredMode.REQUIRED)` annotiert werden.

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/main/java/de/muenchen/oss/wahllokalsystem/monitoringservice/client/waehleranzahl/WaehleranzahlClientMapper.java
> +    @Mapping(target = "wahlID", source = "bezirkUndWahlID.wahlID")
im Altsystem ist es `null`

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/test/resources/http.request/http-client.env.json
> +{
bitte Werte für `token_type` und `auth_token` hinterlegen (analog zu #468 )

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/test/resources/application-test.yml
> +      basePath: http://localhost:${wiremock.server.port}/
```suggestion
```

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/service/waehleranzahl/WaehleranzahlServiceTest.java
> +            val waehleranzahlSetModel = WaehleranzahlModel.builder().build();
```suggestion
        void should_notThrowExceptionAndSaveDataInRepo_when_ModelIsGiven() {
            val waehleranzahlSetModel = WaehleranzahlModel.builder().build();
```

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/service/waehleranzahl/WaehleranzahlServiceTest.java
> +        void should_returnEmptyResult_when_RepoDataNotFound() {
```suggestion
        void should_returnEmptyResult_when_repoDataNotFound() {
```

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/service/waehleranzahl/WaehleranzahlServiceTest.java
> +        void should_returnRepoData_when_RepoDataFound() {
```suggestion
        void should_returnRepoData_when_repoDataFound() {
```

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/service/waehleranzahl/WaehleranzahlServiceSecurityTest.java
> +        void should_FailWithTechnischeWlsException_when_RepoAuthorityIsMissing() throws Exception {
```suggestion
        void should_failWithTechnischeWlsException_when_repoAuthorityIsMissing() throws Exception {
```

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/service/waehleranzahl/WaehleranzahlServiceSecurityTest.java
> +        void should_grantAccessAndThrowNoException_when_AuthoritiesAreValid() {
```suggestion
        void should_grantAccessAndThrowNoException_when_authoritiesAreValid() {
```

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/service/waehleranzahl/WaehleranzahlServiceSecurityTest.java
> +        void should_FailWithAccessDeniedException_when_AnyAuthorityIsMissing(final ArgumentsAccessor argumentsAccessor) {
```suggestion
        void should_failWithAccessDeniedException_when_anyAuthorityIsMissing(final ArgumentsAccessor argumentsAccessor) {
```

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/service/waehleranzahl/WaehleranzahlServiceSecurityTest.java
> +        void should_grantAccessAndThrowNoException_when_AuthoritiesAreValid() throws Exception {
```suggestion
        void should_grantAccessAndThrowNoException_when_authoritiesAreValid() throws Exception {
```

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/service/waehleranzahl/WaehleranzahlServiceSecurityTest.java
> +        void should_FailWithAccessDeniedException_when_ServiceAuthorityIsMissing() throws Exception {
```suggestion
        void should_failWithAccessDeniedException_when_serviceAuthorityIsMissing() throws Exception {
```

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/service/waehleranzahl/WaehleranzahlModelMapperTest.java
> +    void should_returnEqualWaehleranzahlModel_when_WaehleranzahlIsMapped() {
```suggestion
    void should_returnEqualWaehleranzahlModel_when_waehleranzahlIsMapped() {
```

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/service/waehleranzahl/WaehleranzahlModelMapperTest.java
> +    void should_returnEqualWaehleranzahl_when_WaehleranzahlModelIsMapped() {
```suggestion
    void should_returnEqualWaehleranzahl_when_waehleranzahlModelIsMapped() {
```

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/rest/waehleranzahl/WaehleranzahlDTOMapperTest.java
> +        void should_returnNull_when_ModelIsNull() {
```suggestion
        void should_returnNull_when_modelIsNull() {
```

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/rest/waehleranzahl/WaehleranzahlDTOMapperTest.java
> +        void should_returnNull_when_DTOIsNull() {
```suggestion
        void should_returnNull_when_dtoIsNull() {
```

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/rest/waehleranzahl/WaehleranzahlDTOMapperTest.java
> +        void should_returnNull_when_DTOIsNull() {
Dieser Test sollte nicht Teil von `ToDTO` Testsuit sein.

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/rest/waehleranzahl/WaehleranzahlDTOMapperTest.java
> +        void should_mapDtoToModel_when_DtoIsNotNull() {
Dieser Test sollte nicht Teil von `ToDTO` Testsuit sein.

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/rest/waehleranzahl/WaehleranzahlControllerTest.java
> +        void should_returnHttp204AndBodyIsNull_when_serviceIsCalledWithNoData() {
```suggestion
        void should_returnHttp204AndBodyIsNull_when_serviceIsReturnsNoData() {
```

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/rest/waehleranzahl/WaehleranzahlControllerTest.java
> +    class GetWahlbeteiligung {
Es fehlt ein Test dafür dass der Service Daten liefert

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/rest/waehleranzahl/WaehleranzahlControllerTest.java
> +    WaehleranzahlService waehleranzahlService;
```suggestion
public class WaehleranzahlControllerTest {

    @Mock
    WaehleranzahlService waehleranzahlService;
```

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/rest/waehleranzahl/WaehleranzahlControllerIntegrationTest.java
> +    @Nested
```suggestion
    @Nested
```

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/rest/waehleranzahl/WaehleranzahlControllerIntegrationTest.java
> +        void should_returnEmptyResponse_when_NoDataFound() throws Exception {
```suggestion
        void should_returnEmptyResponse_when_noDataFound() throws Exception {
```

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/rest/waehleranzahl/WaehleranzahlControllerIntegrationTest.java
> +        void should_returnOkAndData_when_DataFound() throws Exception {
```suggestion
        void should_returnOkAndData_when_dataFound() throws Exception {
```

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/rest/waehleranzahl/WaehleranzahlControllerIntegrationTest.java
> +            void should_overwriteExistingData_when_NewDataIsStoredWithSameID() throws Exception {
```suggestion
            void should_overwriteExistingData_when_newDataIsStoredWithSameID() throws Exception {
```

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/rest/waehleranzahl/WaehleranzahlControllerIntegrationTest.java
> +    WaehleranzahlClientMapper waehleranzahlClientMapper;
unused

```suggestion
```

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/rest/waehleranzahl/WaehleranzahlControllerIntegrationTest.java
> +            val expectedResponseBody = waehleranzahlDTOMapper.toDTO(waehleranzahlModelMapper.toModel(waehleranzahlToFind));
würde ich nach unten verlagern da es besser bei der Assertion aufgehoben ist

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/rest/waehleranzahl/WaehleranzahlControllerIntegrationTest.java
> +            @Test
```suggestion
        class PostBriefwahlvorbereitung {

            @Test
```

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/rest/waehleranzahl/WaehleranzahlControllerIntegrationTest.java
> +            void should_overwriteExistingData_when_NewDataIsStoredWithSameID() throws Exception {
Der Test sollte vereinfacht werden. Anstatt zwei mal über den Controller zu speichern sollten die bestehenden Daten über das Repo eingegeben werden.

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/rest/waehleranzahl/WaehleranzahlControllerIntegrationTest.java
> +                SecurityUtils.runWith(Authorities.REPOSITORY_READ_WAEHLERANZAHL);
Der Test läuft im no-security Mode, daher sollte das nicht notwendig sein.

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/rest/waehleranzahl/WaehleranzahlControllerIntegrationTest.java
> +        void should_throwTechnischeWlsException_when_requestIsInvalid() throws Exception {
die Exception kommt weil das Speichern fehlschlug und nicht weil die Anfrage invalid ist. Invalide Request haben gibt es nur bei null oder Emptystring für die IDs

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/configuration/SecurityConfigurationTest.java
> +        void should_return401Unauthorized_when_GetWithUnauthorizedAnonymousUser() throws Exception {
```suggestion
        void should_return401Unauthorized_when_getWithUnauthorizedAnonymousUser() throws Exception {
```

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/configuration/SecurityConfigurationTest.java
> +        void should_return204NoContent_when_GetWithAuthorizedMockUser() throws Exception {
```suggestion
        void should_return204NoContent_when_getWithAuthorizedMockUser() throws Exception {
```

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/configuration/SecurityConfigurationTest.java
> +        void should_return401Unauthorized_when_PostWithUnauthorizedAnonymousUser() throws Exception {
```suggestion
        void should_return401Unauthorized_when_postWithUnauthorizedAnonymousUser() throws Exception {
```

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/configuration/SecurityConfigurationTest.java
> +        void should_return200OK_when_PostWithAuthorizedMockUser() throws Exception {
```suggestion
        void should_return200OK_when_postWithAuthorizedMockUser() throws Exception {
```

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/client/waehleranzahl/WaehleranzahlClientImplTest.java
> +            val waehleranzahlModel = new WaehleranzahlModel(new BezirkUndWahlID("wahlID01", "wahlbezirkID01"), 99L, LocalDateTime.now());
```suggestion
        void should_callEaiApiWithDTO_when_clientIsCalledWithModel() {
            val waehleranzahlModel = new WaehleranzahlModel(new BezirkUndWahlID("wahlID01", "wahlbezirkID01"), 99L, LocalDateTime.now());
```

2024-10-22 18:22 UTC, MrSebastian commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/client/waehleranzahl/WaehleranzahlClientImplTest.java
> +            val waehleranzahlModel = new WaehleranzahlModel(new BezirkUndWahlID("wahlID01", "wahlbezirkID01"), 99L, LocalDateTime.now());
```suggestion
        void should_throwTechnischeWlsException_when_eaiApiThrowsAnyException() {
            val waehleranzahlModel = new WaehleranzahlModel(new BezirkUndWahlID("wahlID01", "wahlbezirkID01"), 99L, LocalDateTime.now());
```

2024-10-24 15:10 UTC, Nic12345678 commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/rest/waehleranzahl/WaehleranzahlControllerIntegrationTest.java
> +        class PostBriefwahlvorbereitung {
Warum **_Briefwahlvorbereitung_** und nicht **_Wahlbeteiligung_**?

2024-10-25 10:51 UTC, dragonfly28 commented on wls-monitoring-service/src/main/java/de/muenchen/oss/wahllokalsystem/monitoringservice/client/waehleranzahl/WaehleranzahlClientImpl.java
> +            throw exceptionFactory.createTechnischeWlsException(ExceptionConstants.FAILED_COMMUNICATION_WITH_EAI);
Werfen der technischen Exception ist raus, log.error statt log.info und Text der Message angepasst wie im Altsystem.

2024-10-25 10:52 UTC, dragonfly28 commented on wls-monitoring-service/src/main/java/de/muenchen/oss/wahllokalsystem/monitoringservice/MicroServiceApplication.java
> +                "de.muenchen.oss.wahllokalsystem.wls.common.security"
Entfernt

2024-10-25 10:53 UTC, dragonfly28 commented on stack/keycloak/migration/create-group-all-monitoring-authorities.yml
> +      user: wls_all
wls_all_uwb und wls_all_bwb hinzugefügt, id und author angepasst

2024-10-25 11:00 UTC, dragonfly28 commented on wls-monitoring-service/src/main/java/de/muenchen/oss/wahllokalsystem/monitoringservice/client/waehleranzahl/WaehleranzahlClientMapper.java
> +    @Mapping(target = "wahlID", source = "bezirkUndWahlID.wahlID")
Mapping und Test angepasst

2024-10-25 11:01 UTC, dragonfly28 commented on wls-monitoring-service/src/main/java/de/muenchen/oss/wahllokalsystem/monitoringservice/configuration/BasePathConfiguration.java
> +    private final de.muenchen.oss.wahllokalsystem.monitoringservice.eai.aou.ApiClient eaiApiClient;
Import verwendet

2024-10-25 11:03 UTC, dragonfly28 commented on wls-monitoring-service/src/main/java/de/muenchen/oss/wahllokalsystem/monitoringservice/domain/waehleranzahl/Waehleranzahl.java
> +    private java.time.LocalDateTime uhrzeit;
Import verwendet

2024-10-25 11:29 UTC, dragonfly28 commented on wls-monitoring-service/src/main/resources/application.yml
> +      basePath: http://localhost:39146
Angepasst

2024-10-25 11:29 UTC, Nic12345678 commented on wls-monitoring-service/src/main/java/de/muenchen/oss/wahllokalsystem/monitoringservice/exception/GlobalExceptionHandler.java
👍 Habe so viel gesucht bei mir, weil der MockMvc die Exceptions aus dem Validator nicht abfing .. es fehlte mir der GlobalException Handler :)

2024-10-25 11:57 UTC, dragonfly28 commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/rest/waehleranzahl/WaehleranzahlControllerIntegrationTest.java
> +        class PostBriefwahlvorbereitung {
:-) umbenannt, siehe 3334485304749c2cb06400982315785c5ace1e2e

2024-10-25 13:08 UTC, dragonfly28 commented on wls-monitoring-service/src/main/java/de/muenchen/oss/wahllokalsystem/monitoringservice/service/waehleranzahl/WaehleranzahlValidator.java
> +    public void validWahlIdUndWahlbezirkIDOrThrow(final BezirkUndWahlID bezirkUndWahlID) {
test erstellt, siehe 0864c4298a13145f6132a76334797115213c7e0f

2024-10-25 13:27 UTC, dragonfly28 commented on wls-monitoring-service/src/main/java/de/muenchen/oss/wahllokalsystem/monitoringservice/rest/waehleranzahl/WaehleranzahlDTO.java
> +    @NotNull String wahlbezirkID,
Parameter entfernt, ist schöner so.

siehe edc7596acf0a8ac65bb5ad6bd8f26ec14cb1cbc5

2024-10-25 13:35 UTC, dragonfly28 commented on wls-monitoring-service/src/main/java/de/muenchen/oss/wahllokalsystem/monitoringservice/rest/waehleranzahl/WaehleranzahlDTO.java
> +    @NotNull Long anzahlWaehler,
geändert, siehe b3cb94d8c809f57786cecf7d746ee3ff8e2e58ee

2024-10-25 13:36 UTC, dragonfly28 commented on wls-monitoring-service/src/main/java/de/muenchen/oss/wahllokalsystem/monitoringservice/service/waehleranzahl/WaehleranzahlModel.java
> +    @NotNull Long anzahlWaehler,
geändert, siehe b3cb94d8c809f57786cecf7d746ee3ff8e2e58ee

2024-10-25 13:40 UTC, dragonfly28 commented on wls-monitoring-service/src/main/java/de/muenchen/oss/wahllokalsystem/monitoringservice/rest/waehleranzahl/WaehleranzahlDTO.java
> +    @NotNull Long anzahlWaehler,
Soll das auf long angepasst werden? Ich würde es so lassen.

2024-10-25 13:43 UTC, dragonfly28 commented on wls-monitoring-service/src/test/resources/http.request/http-client.env.json
> +{
sind hinzugefügt,

siehe b4dbcec214c78fd2d0b22302b06651ef28f012c7

2024-10-25 13:48 UTC, dragonfly28 commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/rest/waehleranzahl/WaehleranzahlDTOMapperTest.java
> +        void should_returnNull_when_DTOIsNull() {
nested class toSetModel erstellt und Methoden verschoben, 

siehe 0cd325a648dce4163486e3628a94925e26f37e62

2024-10-28 07:13 UTC, MrSebastian requested changes

2024-10-28 07:13 UTC, MrSebastian commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/service/waehleranzahl/WaehleranzahlValidatorTest.java
> +class WaehleranzahlValidatorTest {
Bitte [Naming-Convetions](https://it-at-m.github.io/Wahllokalsystem/technik/coding_conventions/tests_naming.html) für Tests anwenden.

2024-10-28 07:13 UTC, MrSebastian commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/service/waehleranzahl/WaehleranzahlServiceTest.java
>          void should_notThrowExceptionAndSaveDataInRepo_when_ModelIsGiven() {
```suggestion
        void should_notThrowExceptionAndSaveDataInRepo_when_modelIsGiven() {
```

2024-10-30 08:30 UTC, dragonfly28 commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/rest/waehleranzahl/WaehleranzahlDTOMapperTest.java
> +        void should_mapDtoToModel_when_DtoIsNotNull() {
korrigiert mit 0cd325a648dce4163486e3628a94925e26f37e62

2024-10-30 09:46 UTC, dragonfly28 commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/rest/waehleranzahl/WaehleranzahlControllerTest.java
> +    class GetWahlbeteiligung {
siehe 010e5cbc2aa612d35a184bd2ddfacbf336e611b9

2024-10-30 09:46 UTC, dragonfly28 commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/rest/waehleranzahl/WaehleranzahlControllerIntegrationTest.java
> +            val expectedResponseBody = waehleranzahlDTOMapper.toDTO(waehleranzahlModelMapper.toModel(waehleranzahlToFind));
siehe 010e5cbc2aa612d35a184bd2ddfacbf336e611b9

2024-10-30 09:46 UTC, dragonfly28 commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/rest/waehleranzahl/WaehleranzahlControllerIntegrationTest.java
> +            void should_overwriteExistingData_when_NewDataIsStoredWithSameID() throws Exception {
siehe 010e5cbc2aa612d35a184bd2ddfacbf336e611b9

2024-10-30 09:47 UTC, dragonfly28 commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/service/waehleranzahl/WaehleranzahlValidatorTest.java
> +class WaehleranzahlValidatorTest {
siehe 010e5cbc2aa612d35a184bd2ddfacbf336e611b9

2024-10-30 09:47 UTC, dragonfly28 commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/service/waehleranzahl/WaehleranzahlServiceTest.java
>          void should_notThrowExceptionAndSaveDataInRepo_when_ModelIsGiven() {
siehe 010e5cbc2aa612d35a184bd2ddfacbf336e611b9

2024-10-30 10:10 UTC, dragonfly28 commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/rest/waehleranzahl/WaehleranzahlControllerIntegrationTest.java
> +                SecurityUtils.runWith(Authorities.REPOSITORY_READ_WAEHLERANZAHL);
siehe c44eb211a9e66dcf052b260dcee64ccc2d9dfaaf

2024-10-30 10:10 UTC, dragonfly28 commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/rest/waehleranzahl/WaehleranzahlControllerIntegrationTest.java
> +        void should_throwTechnischeWlsException_when_requestIsInvalid() throws Exception {
siehe c44eb211a9e66dcf052b260dcee64ccc2d9dfaaf

2024-11-04 07:26 UTC, MrSebastian requested changes

2024-11-04 07:26 UTC, MrSebastian commented on wls-monitoring-service/src/main/java/de/muenchen/oss/wahllokalsystem/monitoringservice/client/waehleranzahl/WaehleranzahlClientMapper.java
> +    ZoneOffset DEFAULT_ZONE = ZoneOffset.UTC;
SystemOffset verwenden

```suggestion
    ZoneId DEFAULT_ZONE_ID = ZoneId.systemDefault();
```

2024-11-04 07:26 UTC, MrSebastian commented on wls-monitoring-service/src/main/java/de/muenchen/oss/wahllokalsystem/monitoringservice/client/waehleranzahl/WaehleranzahlClientMapper.java
> +    }
Die zweite Methode ist notwendig um in den Tests zu Zeigen dass es mit Zeitzonen die eine Zeitumstellung haben funktioniert.

`zoneId.getRules().getOffset(localDateTime);` ist notwendig auf Grund der möglichen Zeitumstellung.

```suggestion
    default OffsetDateTime localDateTimeToOffsetDateTime(LocalDateTime localDateTime) {
        return localDateTimeToOffsetDateTime(localDateTime, DEFAULT_ZONE_ID);
    }

    default OffsetDateTime localDateTimeToOffsetDateTime(LocalDateTime localDateTime, ZoneId zoneId) {
        val zoneOffset = zoneId.getRules().getOffset(localDateTime);
        return localDateTime.atOffset(zoneOffset);
    }
```

2024-11-04 07:26 UTC, MrSebastian commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/client/waehleranzahl/WaehleranzahlClientMapperTest.java
> +        void isMappedWithSomething() {
bitte an Namenskonvetion halten.

2024-11-04 07:26 UTC, MrSebastian commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/client/waehleranzahl/WaehleranzahlClientMapperTest.java
> +    }
Tests zu meinem Vorschlag im WaehleranzahlClientMapper

```suggestion
    }

    @Nested
    class LocalDateTimeToOffsetDateTime {

        @Nested
        class WithZoneIdWithDaylightSavingTime {

            @Test
            void should_useSummerSeasonOffset_when_mapping() {
                val localDateTime = LocalDateTime.parse("2024-06-12T12:13:14.567");
                val zoneID = ZoneId.of("Europe/Berlin");

                val result = unitUnderTest.localDateTimeToOffsetDateTime(localDateTime, zoneID);

                val expectedResult = OffsetDateTime.of(localDateTime, ZoneOffset.ofHours(2));
                Assertions.assertThat(result).isEqualTo(expectedResult);
            }

            @Test
            void should_useWinterSeasonOffset_when_mapping() {
                val localDateTime = LocalDateTime.parse("2024-11-12T12:13:14.567");
                val zoneID = ZoneId.of("Europe/Berlin");
                val result = unitUnderTest.localDateTimeToOffsetDateTime(localDateTime, zoneID);

                val expectedResult = OffsetDateTime.of(localDateTime, ZoneOffset.ofHours(1));
                Assertions.assertThat(result).isEqualTo(expectedResult);
            }
        }
    }
```

2024-11-04 07:26 UTC, MrSebastian commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/service/waehleranzahl/WaehleranzahlServiceTest.java
> +    class PostWahlbeteiligung {
Bitte Test ergänzen dass der Client aufgerufen wurde

2024-11-04 11:43 UTC, dragonfly28 commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/client/waehleranzahl/WaehleranzahlClientMapperTest.java
> +        void isMappedWithSomething() {
siehe eefcc74078f1c748e0662fcbf985fde0c3377e6b

2024-11-04 12:10 UTC, dragonfly28 commented on wls-monitoring-service/src/test/java/de/muenchen/oss/wahllokalsystem/monitoringservice/service/waehleranzahl/WaehleranzahlServiceTest.java
> +    class PostWahlbeteiligung {
siehe b6ce4f36e2c95dd179269e7c1fe00d4f2983afbd

2024-11-04 13:04 UTC, MrSebastian approved these changes

2024-11-04 13:30 UTC, merged