176 implementierung user endpoint
it-at-m/Wahllokalsystem pull request #546
Opened 2024-11-14 14:41 UTC by dragonfly28

# Beschreibung:

Abfrage User und Unlock User implementiert.

Für die Abfrage mit den Beispiel-Requests wurde im lokalen Keycloak eine Konfigurationsänderung gemacht damit nicht die UserId sondern der Username im Feld `user_name` durch das Token geliefert wird.
Deshalb muss Keycloak neu aufgesetzt werden.

Abhängig von Issue #547, muss zuerst gelöst und gemerged werden.

## Definition of Done (DoD):

### Backend ###
- [x] Doku aktualisiert
- [x] Swagger-API vollständig
- [x] Unit-Tests gepflegt
- [x] Integrationstests gepflegt
- [x] Beispiel-Requests gepflegt

Closes #176

> [^1]: _Nicht zutreffende Referenzen vor dem Speichern entfernen_

2024-11-14 18:25 UTC, MrSebastian requested changes

2024-11-14 18:25 UTC, MrSebastian commented on wls-auth-service/src/main/java/de/muenchen/oss/wahllokalsystem/authservice/service/UserService.java
> +    public Optional<UserModel> getUser(String name) {
bitte vor die private-Methode verlegen

2024-11-14 18:25 UTC, MrSebastian commented on wls-auth-service/src/main/java/de/muenchen/oss/wahllokalsystem/authservice/rest/UserController.java
> +        return userServiceModel.map(userModel -> ResponseEntity.ok(userDTOMapper.toDTO(userModel))).orElseGet(() -> ResponseEntity.noContent().build());
die alte Methode hat immer OK geliefert und der Body war null falls es den User nicht in der Datenbank gab

2024-11-14 18:25 UTC, MrSebastian commented on wls-auth-service/src/main/java/de/muenchen/oss/wahllokalsystem/authservice/rest/UserController.java
> +    @PreAuthorize("hasAuthority('ROLE_ADMIN_ADMIN')")
zur Einheitlichkeit mit den anderen Services würde ich vorschlagen die Prüfung an den Service zu verlagern. Soweit ich sehen konnte wird die Methode von keiner anderen Stelle verwendet.

2024-11-14 18:25 UTC, MrSebastian commented on wls-auth-service/src/main/java/de/muenchen/oss/wahllokalsystem/authservice/rest/UserController.java
> +    public ResponseEntity<?> unlockUser(@PathVariable("username") String username) {
wenn der Rückgabewert auf `void` geändert wird muss du kein return machen und es kommt per Default `OK`

2024-11-14 18:25 UTC, MrSebastian commented on wls-auth-service/src/test/java/de/muenchen/oss/wahllokalsystem/authservice/rest/UserControllerIntegrationTest.java
> +@SpringBootTest(classes = MicroServiceApplication.class, webEnvironment = SpringBootTest.WebEnvironment.MOCK)
`MOCK` ist default und muss nicht definiert werden

2024-11-14 18:25 UTC, MrSebastian commented on wls-auth-service/src/test/java/de/muenchen/oss/wahllokalsystem/authservice/rest/UserControllerIntegrationTest.java
> +            val response = api.perform(request).andExpect(status().isOk()).andReturn();
```suggestion
            val request = MockMvcRequestBuilders.get("/user");

            val response = api.perform(request).andExpect(status().isOk()).andReturn();
```

2024-11-14 18:25 UTC, MrSebastian commented on wls-auth-service/src/test/java/de/muenchen/oss/wahllokalsystem/authservice/rest/UserControllerIntegrationTest.java
> +        void should_failWith500AndIllegalArgumentException_whenUserNotFound() throws Exception {
```suggestion
        void should_failWith500AndIllegalArgumentException_when_userNotFound() throws Exception {
```

2024-11-14 18:25 UTC, MrSebastian commented on wls-auth-service/src/test/java/de/muenchen/oss/wahllokalsystem/authservice/rest/UserControllerIntegrationTest.java
> +        void should_cacheUser_whenControllerIsCalledMoreThanOnce() throws Exception {
```suggestion
        void should_cacheUser_when_controllerIsCalledMoreThanOnce() throws Exception {
```

2024-11-14 18:25 UTC, MrSebastian commented on wls-auth-service/src/test/java/de/muenchen/oss/wahllokalsystem/authservice/rest/UserControllerIntegrationTest.java
> +        void should_returnUserDTO_whenUserFound() throws Exception {
```suggestion
        void should_returnUserDTO_when_userFound() throws Exception {
```

2024-11-14 18:25 UTC, MrSebastian commented on wls-auth-service/src/test/java/de/muenchen/oss/wahllokalsystem/authservice/rest/UserControllerIntegrationTest.java
> +        void should_returnNoContent_whenNoUserFound() throws Exception {
```suggestion
        void should_returnNoContent_when_noUserFound() throws Exception {
```

2024-11-14 18:25 UTC, MrSebastian commented on wls-auth-service/src/test/java/de/muenchen/oss/wahllokalsystem/authservice/rest/UserControllerIntegrationTest.java
> +        void should_unlockUser_whenUserFound() throws Exception {
```suggestion
        void should_unlockUser_when_userFound() throws Exception {
```

2024-11-14 18:25 UTC, MrSebastian commented on wls-auth-service/src/test/java/de/muenchen/oss/wahllokalsystem/authservice/rest/UserControllerIntegrationTest.java
> +            SecurityUtils.runWith(Authorities.CONTROLLER_UNLOCK_USER);
Die Rechtedefinition kannst du ihn die Annotation `WithMockUser` verlagern

2024-11-14 18:25 UTC, MrSebastian commented on wls-auth-service/src/test/java/de/muenchen/oss/wahllokalsystem/authservice/rest/UserControllerIntegrationTest.java
> +            val request = MockMvcRequestBuilders.post("/user" + "/" + userName + "/unlock").with(csrf());
```suggestion
            val request = MockMvcRequestBuilders.post("/user/" + userName + "/unlock").with(csrf());
```

2024-11-14 18:25 UTC, MrSebastian commented on wls-auth-service/src/test/java/de/muenchen/oss/wahllokalsystem/authservice/rest/UserControllerIntegrationTest.java
> +            val request = MockMvcRequestBuilders.post("/user" + "/" + userName + "/unlock").with(csrf());
```suggestion
            val request = MockMvcRequestBuilders.post("/user/" + userName + "/unlock").with(csrf());
```

2024-11-14 18:25 UTC, MrSebastian commented on wls-auth-service/src/test/java/de/muenchen/oss/wahllokalsystem/authservice/rest/UserControllerTest.java
> +        void should_fail_when_serviceWasNotSuccessful() {
Anstatt von Fail gerne die Exception nennen

2024-11-14 18:25 UTC, MrSebastian commented on wls-auth-service/src/test/java/de/muenchen/oss/wahllokalsystem/authservice/rest/UserDTOMapperTest.java
> +        UserDTOMapper unitUnderTest = Mappers.getMapper(UserDTOMapper.class);
```suggestion
    class ToDTO {
```

2024-11-15 09:59 UTC, dragonfly28 commented on wls-auth-service/src/main/java/de/muenchen/oss/wahllokalsystem/authservice/service/UserService.java
> +    public Optional<UserModel> getUser(String name) {
resolved with b4b99b2d472f7e33b20436d7a554f09a4f99e8a6

2024-11-15 10:08 UTC, dragonfly28 commented on wls-auth-service/src/main/java/de/muenchen/oss/wahllokalsystem/authservice/rest/UserController.java
> +    @PreAuthorize("hasAuthority('ROLE_ADMIN_ADMIN')")
resolved with 10a3b9d4a3e68dd2269aa80cdbd0d080bf8599cf

2024-11-15 10:56 UTC, dragonfly28 commented on wls-auth-service/src/main/java/de/muenchen/oss/wahllokalsystem/authservice/rest/UserController.java
> +        return userServiceModel.map(userModel -> ResponseEntity.ok(userDTOMapper.toDTO(userModel))).orElseGet(() -> ResponseEntity.noContent().build());
resolved with 086a000727d5195e24370f855ca934c254a147e2

2024-11-15 10:57 UTC, dragonfly28 commented on wls-auth-service/src/main/java/de/muenchen/oss/wahllokalsystem/authservice/rest/UserController.java
> +    public ResponseEntity<?> unlockUser(@PathVariable("username") String username) {
resolved with 086a000727d5195e24370f855ca934c254a147e2

2024-11-15 12:47 UTC, dragonfly28 commented on wls-auth-service/src/test/java/de/muenchen/oss/wahllokalsystem/authservice/rest/UserControllerIntegrationTest.java
> +@SpringBootTest(classes = MicroServiceApplication.class, webEnvironment = SpringBootTest.WebEnvironment.MOCK)
resolved with e78a9890b2a15fd8d719b86a6f020a2edd11ce9b

2024-11-15 12:47 UTC, dragonfly28 commented on wls-auth-service/src/test/java/de/muenchen/oss/wahllokalsystem/authservice/rest/UserControllerIntegrationTest.java
> +            SecurityUtils.runWith(Authorities.CONTROLLER_UNLOCK_USER);
resolved with e78a9890b2a15fd8d719b86a6f020a2edd11ce9b

2024-11-15 12:48 UTC, dragonfly28 commented on wls-auth-service/src/test/java/de/muenchen/oss/wahllokalsystem/authservice/rest/UserControllerTest.java
> +        void should_fail_when_serviceWasNotSuccessful() {
resolved with e78a9890b2a15fd8d719b86a6f020a2edd11ce9b

2024-11-15 14:09 UTC, MrSebastian commented on wls-auth-service/src/main/java/de/muenchen/oss/wahllokalsystem/authservice/rest/UserController.java
> +    @PreAuthorize("hasAuthority('ROLE_ADMIN_ADMIN')")
reverted da die Methode im Service doch später (#175) ohne die Beschränkung benötigt wird

2024-11-15 14:12 UTC, MrSebastian approved these changes

2024-11-15 14:13 UTC, merged