571 einrichtung des routing
it-at-m/Wahllokalsystem pull request #595
Opened 2024-11-27 14:39 UTC by vjohnslhm

# Beschreibung:

Beispielhafte implementierung des vue routers.

## Definition of Done (DoD):

### Frontend
- [ ] ~Doku aktualisiert~ - nichts zu dokumentieren
- [ ] ~Unit-Tests gepflegt~ - nichts zu testen
- [ ] ~Komponententests gepflegt~ - nichts zu testen

# Referenzen[^1]:

Closes #571 

> [^1]: _Nicht zutreffende Referenzen vor dem Speichern entfernen_

2024-11-27 14:45 UTC, vjohnslhm commented
@coderabbitai full review

2024-11-27 14:58 UTC, vjohnslhm commented on wls-gui-wahllokalsystem/src/views/ExampleError404View.vue
> +</template>
ist nur exemplarisch deswegen ist die usability vorerst egal

2024-11-27 15:07 UTC, vjohnslhm commented on wls-gui-wahllokalsystem/src/views/ExampleNewRouteView.vue
> +          </p>
ist nur exemplarisch deswegen ist die usability vorerst egal

2024-11-27 15:09 UTC, vjohnslhm commented on wls-gui-wahllokalsystem/src/views/ExampleNewRouteView.vue
> +}
siehe commit [6774fd8](https://github.com/it-at-m/Wahllokalsystem/pull/595/commits/6774fd855c98863bf9adc370d73b43c3c37b7863)

2024-11-29 10:59 UTC, MrSebastian requested changes

2024-11-29 10:59 UTC, MrSebastian commented on wls-gui-wahllokalsystem/src/plugins/router.ts
> +    component: ExampleNewRouteView,
Das der Name aus einer anderen Quelle kommt als die Component finde ich nicht so gut. Du könntest `ExampleNewRouteView.__name` verwenden. Ebenso auch bei den `to`-Attributen.

2024-11-29 15:16 UTC, vjohnslhm commented on wls-gui-wahllokalsystem/src/plugins/router.ts
> +    component: ExampleNewRouteView,
Da wir mit dieser Vorgehensweise einen `Uncaught ReferenceError: can´t access lexical declaration 'ExampleNewRouteView' before initialization` erhalten bleiben wir beim aktuellen Vorgehen.

2024-11-29 15:54 UTC, MrSebastian approved these changes

2024-12-02 07:58 UTC, merged