564 einrichtung backend routen im apigateway
it-at-m/Wahllokalsystem pull request #617
Opened 2024-12-03 15:03 UTC by vjohnslhm

# Beschreibung:

Damit im Frontend aud die einzelnen Services zugegriffen werden kann, wurden die Routen dafür im Apigateway festgelegt.

## Definition of Done (DoD):

### Frontend
- [x] Doku aktualisiert
- [x] lokale ausführung ohne fehlermeldungen

# Referenzen[^1]:

Verwandt mit Issue #564 

> [^1]: _Nicht zutreffende Referenzen vor dem Speichern entfernen_

2024-12-03 15:09 UTC, vjohnslhm commented
@coderabbitai full review

2024-12-03 15:32 UTC, vjohnslhm commented on wls-gui-wahllokalsystem/package.json
> +    "dev": "set NODE_OPTIONS=--max-http-header-size=32000 && vite",
Das Skript ist nur für die lokale Entwicklung relevant und alle Entwickler arbeiten mit Windows-Betriebssystemen, daher ist die Konfiguration so ausreichend. 
**An den Reviewer:** Bitte Conversation resolven, wenn du zustimmst.

2024-12-03 17:42 UTC, MrSebastian requested changes

2024-12-03 17:42 UTC, MrSebastian commented on docs/src/technik/development/index.md
> +        backendServiceN --->|accesses| oracleDB
- `backendServiceN --->|accesses| oracleDB`
- `wlsService --->|persisting|oracleDB`

Wir sollten in beiden Fällen vom gleichen Zugriff reden. Ich habe aber keine Präferenz zwischen `accesses` oder `persisting` oder anderen Begriffen.

2024-12-03 17:42 UTC, MrSebastian commented on stack/docker-compose.yml
> +      - './config:/config'
ich finde `config` als Unterordner im `stack`-Ordner zu generisch. Es sollte erkennbaren Bezug zum Gateway haben. `config` als Ordner im Container finde ich ok.

2024-12-03 17:42 UTC, MrSebastian commented on stack/docker-compose.yml
>        - "host.docker.internal:host-gateway"
Soweit ich es sehen konnte wird es nicht mehr verwendet

```suggestion
```

2024-12-03 17:42 UTC, MrSebastian commented on docs/src/technik/development/index.md
>  > Der Anmeldevorgang muss jedes Mal wiederholt werden, sobald das ApiGateway neu gestartet wird.
Das stimmt so nicht mehr mit der Weiterleitung. Wenn man separat arbeiten, d.h. direkt auf den lokalen Entwicklungsserver geht trifft die Regel noch zu.

2024-12-03 17:42 UTC, MrSebastian commented on wls-gui-wahllokalsystem/package.json
> +    "dev": "set NODE_OPTIONS=--max-http-header-size=32000 && vite",
@vjohnslhm wenn die Lösung so leicht ist, sollten wir sie anwenden. Wir sollten uns dazu einen Non-Windows Entwickler suchen. Falls wir keinen zeitnah finden gerne in ein separates Issue auslagern.

2024-12-04 07:54 UTC, vjohnslhm commented on stack/docker-compose.yml
> +      - './config:/config'
siehe [499a522](https://github.com/it-at-m/Wahllokalsystem/pull/617/commits/499a5220345d93febbeabcf627245b04d3df7f43)

2024-12-04 07:54 UTC, vjohnslhm commented on stack/docker-compose.yml
>        - "host.docker.internal:host-gateway"
siehe [8e3cf42](https://github.com/it-at-m/Wahllokalsystem/pull/617/commits/8e3cf42072f40733776d0f023a819092b8d81f79)

2024-12-04 07:54 UTC, vjohnslhm commented on docs/src/technik/development/index.md
> +        backendServiceN --->|accesses| oracleDB
siehe [ff6b2a6](https://github.com/it-at-m/Wahllokalsystem/pull/617/commits/ff6b2a61f0597bdc9cfe3d049a0c66b116dcc5c9)

2024-12-04 09:39 UTC, vjohnslhm commented on wls-gui-wahllokalsystem/package.json
> +    "dev": "set NODE_OPTIONS=--max-http-header-size=32000 && vite",
Die Fehlermeldung "Request Header Fields Too Large" konnte nicht mehr reproduziert werden, daher wurde die Einstellung vorerst wieder auf das Standardscript `"dev": "vite"` konfiguriert.

siehe [951f6b4](https://github.com/it-at-m/Wahllokalsystem/pull/617/commits/951f6b48f3529cca8d362dfbd0b6399e453a7ea6)

2024-12-04 09:53 UTC, vjohnslhm commented on docs/src/technik/development/index.md
>  > Der Anmeldevorgang muss jedes Mal wiederholt werden, sobald das ApiGateway neu gestartet wird.
angepasst in commit [dfa10e6](https://github.com/it-at-m/Wahllokalsystem/pull/617/commits/dfa10e6a4f850b71fe791b51932eb0ea44f7bba5)

2024-12-04 10:23 UTC, MrSebastian approved these changes

2024-12-04 13:13 UTC, merged