fix SecurityConfig: dont permitAll on all paths
it-at-m/Wahllokalsystem pull request #71
Opened 2024-04-05 07:22 UTC by dragonfly28

# Beschreibung:

In unserer Referenzarchitektur wurde ein Security-Fix eingebracht, der auch in unserem Service berücksichtigt werden muss.

## Definition of Done (DoD):

### Backend ###

nichts weiter zu tun für dieses Issue

- [x] Doku aktualisiert
- [x] Swagger-API vollständig
- [x] Unit-Tests gepflegt
- [x] Integrationstests gepflegt
- [x] Beispiel-Requests gepflegt
- [x] Doku aktualisiert

# Referenzen[^1]:

Verwandt mit Issue #

Closes #70

> [^1]: _Nicht zutreffende Referenzen vor dem Speichern entfernen_

2024-04-05 07:27 UTC, MrSebastian commented
Können wir das bitte noch durch Tests absichern?

2024-04-05 07:54 UTC, dragonfly28 commented
> Können wir das bitte noch durch Tests absichern?

Welche Art von Tests schweben Dir denn da vor? Eigentlich sollte durch den neuen Archetype ja sichergestellt sein, dass dies so korrekt implmentiert ist und nicht durch jeden Service neu getestet werden muss.

2024-04-05 08:03 UTC, MrSebastian commented
> > Können wir das bitte noch durch Tests absichern?
> 
> Welche Art von Tests schweben Dir denn da vor? Eigentlich sollte durch den neuen Archetype ja sichergestellt sein, dass dies so korrekt implmentiert ist und nicht durch jeden Service neu getestet werden muss.

Integrationstests die zeigen dass man auf `/actuator/**` ohne Authentifizierung kommt.

Aus meiner Sicht sollte der Archetype diese Tests mitliefern.

2024-04-08 10:42 UTC, MrSebastian requested changes
bitte modifier entfernen (siehe junit5)

2024-04-08 10:42 UTC, MrSebastian commented on wls-broadcast-service/src/test/java/de/muenchen/oss/wahllokalsystem/configuration/SecuringWebAppTest.java
> +    public void accessUnsecuredResourceActuatorInfoThenOk() throws Exception {
```suggestion
    void accessUnsecuredResourceActuatorInfoThenOk() throws Exception {
```

2024-04-08 10:42 UTC, MrSebastian commented on wls-broadcast-service/src/test/java/de/muenchen/oss/wahllokalsystem/configuration/SecuringWebAppTest.java
> +    public void accessUnsecuredResourceActuatorMetricsThenOk() throws Exception {
```suggestion
    void accessUnsecuredResourceActuatorMetricsThenOk() throws Exception {
```

2024-04-08 10:42 UTC, MrSebastian commented on wls-broadcast-service/src/test/java/de/muenchen/oss/wahllokalsystem/configuration/SecuringWebAppTest.java
> +    public void accessSecuredResourceRootThenUnauthorized() throws Exception {
```suggestion
    void accessSecuredResourceRootThenUnauthorized() throws Exception {
```

2024-04-08 10:47 UTC, MrSebastian approved these changes

2024-04-08 10:48 UTC, merged